pingcap/tidb-ansible

README.md
README:  add zh_cn tutorial link
=> README:  add zh_cn tutorial link

inventory.ini, roles/bootstrap/tasks/root_tasks.yml
add set_hostname variable in inventory.ini, default value is False
=> add set_hostname variable, default False

README.md, conf/packages.yml, roles/local/tasks/main.yml, roles/pre-ansible/defaults/main.yml
update third_party_packages download url to qiniu under gfw.
=> local_prepare: update third_party_packages url to qiniu

scripts/pd.json, scripts/tidb.json, scripts/tikv.json
=> grafana: rc3 update conf

library/coreos_facts
modify library cores_facts @andelf @LinuxGit PTAL
=> modify library cores_facts

bootstrap.yml, conf/packages.yml
=> bootstrap: fix typo

roles/bootstrap/tasks/root_tasks.yml
- fix regular expression to replace if found, original regex will add redundant configure item.
=> fix regular expression to replace if found

roles/tidb/vars/default.yml
change tidb default lease to 10
=> change tidb default lease to 10

scripts/node.json
grafana: Node Export add node_sockstat_TCP_inuse
=> grafana: Node Export add node_sockstat_TCP_inuse

scripts/grafana-config-copy.py, scripts/privotal.json, start.yml
Add monitor dashboard.
@LinuxGit  @andelf  PTAL
=> add monitor dashboard

roles/grafana/templates/data_source.json.j2, roles/pd/tasks/main.yml, roles/pd/templates/pd.toml.j2, roles/pd/templates/run_pd.sh.j2, roles/prometheus/templates/prometheus.yml.j2, roles/pump/templates/run_pump.sh.j2, roles/tidb/templates/run_tidb.sh.j2, roles/tikv/tasks/main.yml, roles/tikv/templates/run_tikv.sh.j2, rolling_update.yml, start.yml, unsafe_cleanup_data.yml, unsafe_restart.yml
get ip address from inventory.ini, fix get public ip when server has multiple interfaces and default route interface's ip is public ip. 
```
hostvars[inventory_hostname].ansible_host | default(hostvars[inventory_hostname].inventory_hostname)
```
=> get ip address from inventory.ini

roles/local/tasks/main.yml
local prepare: add curl connect timeout in case of bad network
=> local prepare: add curl connect timeout

scripts/tikv.json
grafana: tikv.json grpc update
=> grafana: tikv.json grpc update

scripts/grafana-config-copy.py, scripts/overview.json, start.yml
change the name of grafana dashboard from privotal to overview
@LinuxGit  PTAL
=> change the name of grafana dashboard from privotal to overview

inventory.ini, roles/pd/defaults/main.yml, roles/pd/tasks/main.yml, roles/tikv/defaults/main.yml, roles/tikv/tasks/main.yml
add config labels
@LinuxGit @andelf  PTAL
=> add config labels

roles/tikv/vars/default.yml, scripts/overview.json, scripts/tidb.json
1、Modify grafana metrics
2、Set sync-log, default value is false
=> modify grafana metrics and sync-log

group_vars/all.yml
It causes the modification of cluster_name in inventory.ini not to work
@LinuxGit  PTAL
=> delete the variable named cluster_name from group_vars/all.yml

scripts/node.json, scripts/tikv.json
- Node Export: add Allocated File Descriptor and Maximum  File Descriptor
- TiKV: update unit
=> grafana: add fd descriptor count

scripts/tikv.json
grafana: tikv remove tikv_coprocessor_scan_inefficiency_bucket
=> grafana: tikv remove tikv_coprocessor_scan_inefficiency_bucket

scripts/tikv.json
update grafana tikv.json
@LinuxGit @buggithubs PTAL
=> update grafana tikv.json

roles/check_config_static/tasks/main.yml
=> modify check_config_static

conf/tikv.yml, roles/tikv/vars/default.yml
refer to https://github.com/pingcap/tikv/blob/master/etc/config-template.toml#L76
=> tikv: change default region size

roles/bootstrap/tasks/root_tasks.yml, roles/tikv/defaults/main.yml, roles/tikv/tasks/main.yml
=> add wal_dir config

unsafe_cleanup.yml, unsafe_cleanup_data.yml
=> modify clean yml

roles/tikv/tasks/main.yml
=> modify wal config

roles/check_config_dynamic/tasks/main.yml
Add function to check if XFS file system has bug.
The variable is enable_check_xfs, and the default value is true.
If you need to close it, set 'enable_check_xfs = False' in inventory.ini.
=> add xfs check

roles/pd/templates/run_pd.sh.j2
modify 0.0.0.0:2379 and 0.0.0.0:2380 in run_pd.sh
=> modify ip 0.0.0.0 in run_pd.sh

scripts/node.json
Sorry, the diff seems impossible to review.
=> add ioutil

roles/check_config_dynamic/tasks/main.yml
- check xfs only on tikv_servers
- fix debug messages
=> fix check xfs

conf/tikv.yml, roles/tikv/vars/default.yml
refer: https://github.com/pingcap/tikv/pull/2082
=> tikv: add max-background-jobs

scripts/tikv.json
update tikv dashboard in grafana
=> update tikv dashboard in grafana

roles/pd/defaults/main.yml, roles/pd/templates/run_pd.sh.j2, roles/tidb/defaults/main.yml, roles/tidb/templates/run_tidb.sh.j2, roles/tikv/defaults/main.yml, roles/tikv/templates/run_tikv.sh.j2
redirect tidb/tikv/pd stderr to separate log file.
=> script: redirect stderr

scripts/node.json
Add a row for I/O:
- I/O Through
- I/O Util
- I/O in Progress
- I/O Average Read Time
- I/O Average Write Time
=> Add I/O row: through, util, queue, read/write time

inventory.ini, roles/local/tasks/main.yml, roles/local/templates/packages.yml.j2
Add tidb version optional feature
=> Add tidb version optional feature

rolling_update.yml, start.yml, unsafe_restart.yml
refer: https://github.com/pingcap/tidb/blob/2e7db3da8375028ca96d4d4e54e881cda10505f8/mysql/const.go#L498
=> change tidb wait_for search string

filter_plugins/tags.py, roles/tikv/templates/tikv.toml.j2
tikv/tags: new tikv labels config tag
=> tikv/tags: new tikv labels config tag

conf/tikv.yml, roles/check_config_dynamic/defaults/main.yml, roles/tikv/templates/tikv.toml.j2, roles/tikv/vars/default.yml, scripts/tikv.json
see https://github.com/pingcap/tikv/pull/2054
=> tikv: update config for raft rocksdb

roles/bootstrap/tasks/root_tasks.yml, roles/tikv/defaults/main.yml, roles/tikv/tasks/main.yml, unsafe_cleanup.yml, unsafe_cleanup_data.yml
add tikv config
@LinuxGit @buggithubs PTAL
=> add tikv config

roles/tidb/templates/run_tidb.sh.j2
close tidb auto analyze
@sunhao2017 PTAL
=> close tidb auto analyze

conf/tidb.yml, roles/tidb/vars/default.yml
refer to https://github.com/pingcap/tidb/pull/4630/files
=> tidb conf update

inventory.ini
modify monitored
@LinuxGit @buggithubs PTAL
=> modify monitored

conf/spark-defaults.yml, filter_plugins/tags.py, roles/tispark/tasks/standalone.yml, roles/tispark/templates/spark-defaults.conf.j2, roles/tispark/templates/spark-env.sh.j2
modify spark conf
@LinuxGit @buggithubs PTAL
=> modify spark conf

filter_plugins/tags.py, roles/tispark/templates/spark-defaults.conf.j2, roles/tispark/templates/spark-env.sh.j2
=> modify spark

scripts/tikv.json
Address commet https://github.com/pingcap/tidb-ansible/pull/134#discussion_r141806321
=> Fix storage batch size avg formula

scripts/tidb.json
Update metrics according to this [pr](https://github.com/pingcap/tidb/pull/4793)
=> grafana: add tidb metrics for auto analyze

scripts/pd.json
It should be merged after https://github.com/pingcap/pd/pull/810
=> grafana: update pd metrics.

roles/machine_benchmark/defaults/main.yml, roles/machine_benchmark/tasks/main.yml
=> make machine_benchmark's code more refined

scripts/pd.json
It should be merged after pingcap/pd#814
=> grafana: update pd metrics

roles/systemd/templates/systemd_binary.service.j2, roles/systemd/templates/systemd_docker.service.j2
fix err while starting on boot: start request repeated too quickly for systemd service
=> systemd: add RestartSec

roles/machine_benchmark/tasks/main.yml
fix https://github.com/pingcap/tidb-ansible/issues/164
=> dd: set default decimal separator

scripts/pd.json, scripts/pdn.json
add hot read metrics.PTAL @disksing
=> script/pd: add hot read metrics

scripts/pd.json
change pd_schedule_operators_count
remove tikv_pd_msg_send_duration_seconds_count
=> [Grafana] remove pd.json invalid metrocs

scripts/tikv.json
@BusyJay @siddontang PTAL
Close #173
=> scripts/tikv.json: fix tikv_coprocessor_scan_keys

scripts/node.json
update grafana dashboard node_exporter
=> update grafana dashboard

fetch_logfile.yml, roles/fetch_logfile/tasks/main.yml, roles/fetch_logfile/tasks/root_tasks.yml
update fetch logfile
@LinuxGit PTAL
=> update fetch logfile

scripts/overview.json, scripts/pd.json
update grafana overview dashboard
@LinuxGit PTAL
=> update grafana overview dashboard

roles/supervise/templates/start_role.sh.j2, roles/supervise/templates/stop_role.sh.j2
modify start_role.sh.j2 and stop_role.sh.j2
@LinuxGit PTAL
=> modify start_role.sh.j2 and stop_role.sh.j2

scripts/pd.json
update pd dashboard
@LinuxGit PTAL
=> update pd dashboard

roles/grafana/templates/run_grafana_binary.sh.j2
=> fix grafana lang error

deploy.yml, inventory.ini, roles/check_config_static/tasks/main.yml, roles/local/templates/docker_packages.yml.j2, roles/node_exporter/templates/run_node_exporter_docker.sh.j2, roles/pre-ansible/tasks/main.yml, rolling_update.yml, rolling_update_monitor.yml, unsafe_cleanup_container.yml, unsafe_cleanup_data.yml
- KV mode: add deploy_without_tidb switch
- add rolling_update_monitor.yml
- node_exporter: use host pid namespace
- prom: v2.0.0
=> add rolling_update_monitor.yml and KV mode

scripts/drainer.json, scripts/syncer.json
=> binlog grafana

scripts/pd.json
=> update pd grafana template.

scripts/tidb.json
@LinuxGit 
Seems I was using a newer version of granafa to generate the config. Not sure if it is safe to update its version.
=> grafana: update tidb.

stop.yml
modify stop.yml
@LinuxGit  PTAL
=> modify stop.yml

roles/blackbox_exporter/tasks/binary_deployment.yml
fix blackbox_exporter roles
@LinuxGit PTAL
=> fix blackbox_exporter roles

ansible.cfg, callback_plugins/help.py
When there's no fail tasks,  print "Congrats! All goes well. :-)".
```
PLAY RECAP **************************************************************************************************************************************************
172.16.10.49               : ok=24   changed=5    unreachable=0    failed=0
172.16.10.50               : ok=21   changed=3    unreachable=0    failed=0
172.16.10.61               : ok=21   changed=3    unreachable=0    failed=0
172.16.10.62               : ok=21   changed=3    unreachable=0    failed=0
localhost                  : ok=1    changed=0    unreachable=0    failed=0
Congrats! All goes well. :-)
```
Or print ERROR MESSAGE SUMMARY and help message:
```
ERROR MESSAGE SUMMARY *********************************************************************************** …
```
=> develop a help plugin

roles/prometheus/files/alert.rules.yml, roles/prometheus/tasks/main.yml
update prometheus alert rules
@LinuxGit @jomenxiao  PTAL
=> update prometheus alert rules

roles/prometheus/files/alert.rules.yml, roles/prometheus/tasks/main.yml
updata release-1.0 prometheus alert rules
@LinuxGit @jomenxiao PTAL
=> updata release-1.0 prometheus alert rules

scripts/tikv.json
=> add metrics on gc

roles/tikv/vars/default.yml
Change sync-log default to true
=> Change sync-log default to true

roles/tikv/vars/default.yml
Change sync-log default to true. release-1.0-binlog-local
=> Change sync-log default to true. release-1.0-binlog-local

roles/tikv/vars/default.yml
Change sync-log default to true. release-1.0
=> Change sync-log default to true. release-1.0

inventory.ini
modify tidb version in inventory.ini - release-1.0
=> modify tidb version in inventory.ini - release-1.0

inventory.ini, roles/local/templates/packages.yml.j2
modify tidb version in inventory.ini - release-1.0-binlog-local
=> modify tidb version in inventory.ini - release-1.0-binlog-local

scripts/pd.json
1. fix wrong datasource name.
2. update metadata panel.
=> grafana: update pd template.

scripts/tikv.json
Add 2 panels: peer pending time and apply wait time.
=> add panels for peer pending time and apply wait time.

conf/tikv.yml, roles/tikv/templates/tikv.toml.j2, roles/tikv/vars/default.yml
TiKV introduced a "read pool" and new configuration sections are added.
Related TiKV PR: https://github.com/pingcap/tikv/pull/2713
=> Add read pool related configurations

scripts/pd.json
It should be merged after pingcap/pd#980
=> grafana: add operator step duration metrics

get_store_id.yml, get_store_id_tls.yml, rolling_update.yml, start.yml
Ansible's skipped tasks still register to the variable, so I add include_tasks.
=> rolling_update.yml add include_tasks

scripts/tikv.json
=> grafana: update coprocessor && grpc

scripts/tikv.json
=> update tikv Raft

scripts/tikv.json
=> grafana: update grpc

conf/spark-defaults.yml, roles/tispark/templates/spark-defaults.conf.j2
update pd port mistake of tispark
change peer port to client port
add tispark index allow
=> update pd port mistake of tispark

conf/spark-defaults.yml
=> close tispark index

conf/tidb.yml, conf/tikv.yml, roles/tidb/vars/default.yml, roles/tikv/vars/default.yml
See:
https://github.com/pingcap/tidb/pull/6085
https://github.com/pingcap/tikv/pull/2884
https://github.com/pingcap/tikv/pull/2839
=> update tikv/tidb config

scripts/tikv.json
=> update tikv metrics

scripts/tidb.json
remove invalid alert data and add span for panel
=> fix-tidb-json

roles/bootstrap/tasks/main.yml, roles/check_config_dynamic/tasks/main.yml, roles/check_config_static/tasks/main.yml, roles/check_system_necessary/tasks/main.yml, roles/check_system_optional/tasks/main.yml
=> refine check

conf/tikv.yml, roles/tikv/templates/tikv.toml.j2, roles/tikv/vars/default.yml, rolling_update.yml, start.yml
Related PR: https://github.com/pingcap/tikv/pull/2827
@LinuxGit PTAL
=> Update config and deployment script for Coprocessor Readpool

scripts/tidb.json
rename panic panel to uncommon error, move plan cache to query detial, add critical error to uncommon error.
=> update grafana for release 2.0

scripts/tikv_instances.json
tikv_storage_rawkv_command_total will be dropped in TiKV: https://github.com/pingcap/tikv/pull/2973
=> Remove rawkv_command_total

scripts/tidb.json
Cherry pick 3 commits from release-2.0 branch
=> Refine tidb grafana

scripts/loader.json
=> scripts: add loader grafana template

README.md
=> readme: update wording

scripts/reparo.json
=> scripts: add reparo grafana template file

conf/tidb.yml, roles/tidb/vars/default.yml
refer to https://github.com/pingcap/tidb/pull/6369
=> tidb: remove retry-limit config

conf/tidb.yml, roles/tidb/vars/default.yml
refer to https://github.com/pingcap/tidb/pull/6455
=> tidb remove auto-analyze-ratio config

conf/tidb.yml, roles/tidb/templates/tidb.toml.j2, roles/tidb/vars/default.yml
refer to https://github.com/pingcap/tidb/pull/6503
=> tidb binlog config

inventory.ini
update tidb version to v2.0.2 - release-2.0
=> update tidb version - release-2.0

scripts/tikv.json
=> TiKV: fix incorrect panel title

scripts/tikv.json
Add a panel to show raft log speed.
=> add raft log speed panel.

get_pd_leader.yml, get_pd_leader_tls.yml, rolling_update.yml
rolling_update: 
tidb-ansible will transfer pd leader to another pd server when applying a rolling update for pd servers.
=> rolling_update: transfer pd leader

rolling_update.yml
rolling_update：
transfer PD leader to another PD server only when pd servers >= 3
=> rolling_update: check pd servers count

scripts/node.json
Add page/swap in/out, alloc/comact stall, page dirty and major/minor fault
PTAL @liubo0127 @LinuxGit
=> add some vmstat statistics

conf/tidb.yml
update default config for tidb after https://github.com/pingcap/tidb/pull/6843 merged
=> conf: update tidb default config

scripts/tidb.json
add `instance` from Failed Query OPM
=> scripts: alter metrics add instance for Failed Query OPM metrics

scripts/tikv.json
Add threads state in tikv's Thread CPU section.
=> scripts/tikv: add threads state

scripts/tikv.json, scripts/tikv_instances.json
TiKV PR: https://github.com/pingcap/tikv/pull/3236
=> Add PerfContext Metrics & Adjust Some Other Metrics

conf/pd.yml, conf/tidb.yml, roles/pd/tasks/main.yml, roles/pd/vars/default.yml, roles/prometheus/templates/prometheus.yml.j2, roles/tidb/tasks/main.yml, roles/tidb/vars/default.yml
monitor:
- prometheus pulls tidb/pd metrics
- remove tidb/pd pushgateway config
=> monitor: pull tidb/pd metrics

group_vars/all.yml, roles/bootstrap/tasks/main.yml, roles/check_config_dynamic/tasks/main.yml, roles/check_system_necessary/tasks/main.yml, roles/check_system_optional/tasks/main.yml, scripts/check/check_cpufreq.py
check:
- check if CPU frequency governor is set to "performance" mode
- remove deploy_user task
=> check: CPU frequency governor

conf/tikv.yml, roles/tikv/vars/default.yml
ref: https://github.com/pingcap/tikv/pull/3283
=> tikv: Enlarge the total slots of scheduler latch

conf/pd.yml, roles/pd/vars/default.yml
refer: https://github.com/pingcap/pd/pull/1144
=> pd: use ApproximateKeys instead of ApproximateRows

create_users.yml, deploy_ntp.yml
refer: https://github.com/pingcap/docs-cn/pull/814
=> deploy_ntp/create_users: remove root remote user limit

conf/tidb.yml, roles/tidb/vars/default.yml
https://github.com/pingcap/tidb/pull/7100
=> Add keep-alive settings

conf/tidb.yml, roles/tidb/vars/default.yml
https://github.com/pingcap/tidb/pull/7099
=> [release-2.0] Add keep alive settings

scripts/tikv.json
Cc https://github.com/pingcap/tikv/pull/3338
=> scripts/tikv: add threads io

scripts/pd.json
related PD PR: https://github.com/pingcap/pd/pull/1172
=> script/pd: add etcd raft states metrics

roles/systemd/templates/systemd_binary.service.j2, roles/systemd/templates/systemd_docker.service.j2
consistent with limits.conf, see https://github.com/pingcap/tidb-ansible/blob/master/roles/bootstrap/tasks/root_tasks.yml#L31
=> systemd: add LimitSTACK config

roles/prometheus/files/blacker.rules.yml, roles/prometheus/files/kafka.rules.yml
update blacker rules
@LinuxGit PTAL
=> update blacker rules

scripts/tidb.json
Add get token duration metrics
Ref: https://github.com/pingcap/tidb/pull/7110
@coocood @shenli
=> grafana: update tidb.json

conf/tikv.yml, roles/tikv/vars/default.yml
refer: https://github.com/tikv/tikv/pull/3317/files
=> tikv: add region-max-keys config

scripts/tikv.json
=> Grafana: update tikv.json, fix rocksdb CPU metrics

conf/tikv.yml, roles/tikv/vars/default.yml
refer: https://github.com/tikv/tikv/pull/3533/files
=> tikv: add grpc-keepalive-time and grpc-keepalive-timeout config

conf/tikv.yml, roles/tikv/vars/default.yml
https://github.com/tikv/tikv/pull/3507
=> TiKV #3507 Configuration Change

clean_log_cron.yml, group_vars/all.yml, roles/clean_log_pd/tasks/add_cron.yml, roles/clean_log_pd/tasks/del_cron.yml, roles/clean_log_pd/tasks/main.yml, roles/clean_log_tidb/tasks/add_cron.yml, roles/clean_log_tidb/tasks/del_cron.yml, roles/clean_log_tidb/tasks/main.yml, roles/clean_log_tikv/tasks/add_cron.yml, roles/clean_log_tikv/tasks/del_cron.yml, roles/clean_log_tikv/tasks/main.yml
=> add log clean

deploy_ntp.yml
- deploy_ntp.yml: add support for AWS Amazon Linux 2 AMI image
=> playbook: update deploy_ntp.yml

scripts/tidb.json
=> add slow log metric panel

roles/systemd/templates/systemd_binary.service.j2
systemd: add MemoryLimit setting
@LinuxGit @superlzs0476 PTAL
=> systemd: add MemoryLimit setting

roles/machine_benchmark/tasks/fio_randread_write.yml, roles/machine_benchmark/tasks/fio_randread_write_latency.yml, roles/machine_benchmark/tasks/main.yml
=> Fix randread and sequential write benchmark for latency

conf/tidb.yml, roles/tidb/vars/default.yml
=> Adjust tidb's txn_local_latches default parameters enabled and capacity

scripts/tikv.json
Based on TiKV [PR 3657](https://github.com/tikv/tikv/pull/3657)
=> Add duration of raft store events to metrics;

inventory.ini
=> Modify TiDB version information

roles/prometheus/files/lightning.rules.yml, roles/prometheus/tasks/main.yml, roles/prometheus/templates/prometheus.yml.j2, rolling_update_monitor.yml, scripts/grafana-config-copy.py, scripts/lightning.json, start.yml
add lightning monitor dashboard and alert
@LinuxGit @kennytm PTAL
=> add lightning monitor dashboard and alert

common_tasks/get_store_id.yml
=> Fix check get store id is undefined result output

conf/tikv.yml, roles/tikv/vars/default.yml
These two TiKV PRs updated configurations:
- https://github.com/tikv/tikv/pull/3729
- https://github.com/tikv/tikv/pull/3752
Please do not merge this PR until both PRs are merged.
=> Update TiKV config

scripts/binlog.json
binlog.json: add binlog_drainer_queue_size metrics
=> binlog.json: add binlog_drainer_queue_size metrics

conf/tikv.yml, roles/tikv/vars/default.yml
=> Cheery Pick TiKV Config from #402

scripts/binlog.json
merge after https://github.com/pingcap/tidb-binlog/pull/394 and https://github.com/pingcap/tidb-binlog/pull/393
=> binlog.json: add queue size and query histogram

group_vars/all.yml, group_vars/drainer_servers.yml, group_vars/pump_servers.yml, roles/systemd/templates/systemd_binary.service.j2, roles/systemd/templates/systemd_docker.service.j2
=> Update systemd, specify when to restart the service

roles/bootstrap/tasks/main.yml, roles/check_system_static/tasks/main.yml
=> Add gather_timeout parameter

group_vars/all.yml, group_vars/drainer_servers.yml, group_vars/pump_servers.yml, roles/drainer/defaults/main.yml, roles/pump/defaults/main.yml, roles/supervise/templates/stop_role.sh.j2, roles/systemd/templates/systemd_binary.service.j2, roles/tidb/defaults/main.yml
=> Update the stop and restart behavior of systemd

roles/supervise/templates/stop_role.sh.j2, roles/systemd/templates/systemd_binary.service.j2, roles/tidb/defaults/main.yml
=> Update the stop behavior of systemd

scripts/tikv.json
=> tikv.json: unify the metrics name

scripts/tikv.json
Show compaction reason in grafana. The following graph show the result.
=> Show compaction reason in grafana

roles/tidb_lightning/templates/tidb-lightning.toml.j2
=> Importer one of  PD addresses

conf/tidb.yml, roles/tidb/vars/default.yml
=> Add tidb's tikv-client default parameter max-txn-time-use

roles/local/templates/common_packages.yml.j2
=> Remove download of tidb-tools

scripts/tikv.json
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>
=> reorg compaction reason position

scripts/tidb.json
change 'DDL OPM' to 'DDL META OPM', which may lead to misunderstanding.
=> scripts: change title 'DDL OPM' to 'DDL META OPM' to dissolve misunderstandings

scripts/pd.json
=> scripts: update pd metrics

scripts/tikv_pull.json, scripts/tikv_push.json
This PR is going to fix the problem which the metrics of a single TiKV can't be displayed in Grafana.
=> scripts: fix the single TiKV metrics

rolling_update.yml
=> rolling update pump

conf/tidb.yml, conf/tikv.yml, inventory.ini, roles/tidb/vars/default.yml, roles/tikv/vars/default.yml
@liubo0127  @LinuxGit @hicqu @GregoryIan  PTAL
=> Update version to v2.1.4

conf/tidb.yml, conf/tikv.yml, inventory.ini, roles/tidb/vars/default.yml, roles/tikv/vars/default.yml
Reverts pingcap/tidb-ansible#679
=> Revert "Update version to v2.1.4"

common_tasks/get_pd_name.yml, graceful_stop.yml, roles/pd/templates/run_pd_binary.sh.j2, rolling_update.yml
change pd name from pd_name_prefix[n] to pd_name_prefix.hostname
=> change pd name to pd.hostname(#675)

scripts/overview.json
This PR is going to fix the metrics in the overview dashboard.
=> scripts: fix the overview metrics

scripts/overview.json
=> scripts: fix the overview metrics (#677)

scripts/tidb.json
update tidb.json for counter `SignificantFeedbackCounter` to show the high update rate feedback change.
=> scripts: update tidb.json

scripts/tikv_pull.json, scripts/tikv_push.json
Signed-off-by: 5kbpers <tangminghua@pingcap.com>
=> add thread context switches metrics panel

common_tasks/get_pd_name.yml, graceful_stop.yml, roles/pd/templates/run_pd_binary.sh.j2, rolling_update.yml
change pd name to pd.hostname(#675) (#683)
=> cherry pick from (#683)

conf/tidb.yml, conf/tikv.yml, roles/tidb/vars/default.yml, roles/tikv/vars/default.yml
=> Add configuration parameters

rolling_update.yml
=> fix cluster mode pump rolling update

scripts/pd.json
This PR is related to pingcap/pd#1429.
=> scripts: use address instead of store in PD

scripts/tikv_pull.json
=> tikv: add critical error metrics

scripts/tikv_pull.json, scripts/tikv_push.json
fix some parameters of thread context switches panel.
=> tikv: fix thread context switches panel

roles/systemd/templates/systemd_binary.service.j2
* add CPUQuota setting to systemd
* add IO(Read|Write)BandwidthMax setting to systemd
=> Add more resource control settings (#708)

group_vars/alertmanager_servers.yml, roles/alertmanager/templates/run_alertmanager_docker.sh.j2
=> Modify AlertManager default port and script

group_vars/monitoring_servers.yml, roles/prometheus/defaults/main.yml
=> Set prometheus monitoring data retention time 30d

conf/tikv.yml, roles/tikv/vars/default.yml
Signed-off-by: fredchenbj <cfworking@163.com>
Refer to a tikv pr: https://github.com/tikv/tikv/pull/4335 , add some rocksdb auto-tuned parameters config.
=> config: add auto-tuned parameters config

conf/tidb.yml, roles/tidb/vars/default.yml
=> Add tidb parameter

excessive_rolling_update.yml
=> Over-upgrade from versions prior to 3.0 (#718)

requirements.txt, roles/grafana/defaults/main.yml, roles/local/templates/binary_packages.yml.j2, roles/prometheus/defaults/main.yml
@superlzs0476  PTAL
I have tested it, but it is better to test it again.
=> Modify the version of ansible, grafana, and promethues

group_vars/all.yml
=> Add cgroup restrictions

excessive_rolling_update.yml, rolling_update.yml
Upgrading from **2.0.1 and previous versions** to **2.1.x and master or later versions** is forbidden
@superlzs0476 @winkyao @LinuxGit PTAL
=> Set rolling update limits

roles/check_system_static/tasks/main.yml
=> Update os version limit (#732)

inventory.ini, roles/tidb/templates/run_tidb_binary.sh.j2
=> Adjust slow query configure

roles/check_system_dynamic/tasks/main.yml, roles/check_system_static/tasks/main.yml, roles/tikv/tasks/check_filesystem.yml
=> Update document links, compatible with new version documentation

conf/tidb.yml, roles/tidb/vars/default.yml
@liubo0127  PTAL
remove "max-txn-time-use" parameter from tidb-ansible.
=> rm tidb of parameter about max-txn-time-use

scripts/grafana-config-copy.py, scripts/tikv_details.json, scripts/tikv_summary.json, scripts/tikv_trouble_shooting.json
- Add Write Stall trouble shooting
- Remove duplicated grafana for TiKV Details
- Add .999 for trouble shooting
=> simplify tikv grafana

excessive_rolling_update.yml, rolling_update.yml
=> Update rolling update version limit

conf/tikv.yml, roles/tikv/templates/tikv.toml.j2, roles/tikv/vars/default.yml
Update tikv config template to reflect shared block cache change in https://github.com/tikv/tikv/pull/4563
Tested by deploy and start a cluster.
=> config: add shared block cache config

roles/local/tasks/main.yml, roles/local/templates/common_packages.yml.j2
=> Adjust local_prepare.yml about TiDB and TiDB Toolkit download task.

conf/tikv.yml, roles/tikv/vars/default.yml
=> tikv: increase raftdb max-background-job and max sub compactions

conf/drainer.toml, conf/pump.yml, roles/pump/templates/pump.toml.j2, roles/pump/vars/default.yml
=> Adjust default configuration of drainer.

roles/tikv/templates/tikv.toml.j2
=> Fix tikv.toml.j2

scripts/tidb.json
=> grafana: add tidb ideal qps and hide it by default

scripts/pd.json
demo: http://172.16.4.4:31731/dashboard/db/test-cluster-pd-new2
Signed-off-by: nolouch <nolouch@gmail.com>
=> *: update pd metrics

scripts/tikv_details.json
TiKV PR: https://github.com/tikv/tikv/pull/4852
=> add metrics of pessimistic transaction

scripts/tikv_details.json
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>
=> distinguish ingest duration by db

scripts/tikv_details.json
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>
=> distinguish stall db when encounter busy error

conf/pd.yml, roles/pd/vars/default.yml
Cc https://github.com/pingcap/pd/pull/1564
=> pd: add two way merge config

conf/tidb.yml, conf/tikv.yml, roles/tidb/vars/default.yml, roles/tikv/vars/default.yml
=> Add pessimistic-txn configs

conf/tikv.yml, roles/tikv/vars/default.yml
=> fix tikv config syntax

group_vars/alertmanager_servers.yml, requirements.txt, roles/alertmanager/templates/run_alertmanager_binary.sh.j2, roles/alertmanager/templates/run_alertmanager_docker.sh.j2, roles/grafana/defaults/main.yml, roles/grafana/tasks/binary_deployment.yml, roles/local/templates/binary_packages.yml.j2, roles/prometheus/files/node.rules.yml, scripts/node.json, scripts/overview.json, scripts/tidb.json
=> Update version and dashboard for the monitor

group_vars/alertmanager_servers.yml, requirements.txt, roles/alertmanager/templates/run_alertmanager_binary.sh.j2, roles/alertmanager/templates/run_alertmanager_docker.sh.j2, roles/grafana/defaults/main.yml, roles/grafana/tasks/binary_deployment.yml, roles/local/templates/binary_packages.yml.j2, roles/prometheus/files/node.rules.yml, scripts/node.json, scripts/overview.json, scripts/tidb.json
* Update the version of some services
* fix dashboard
* Update node_exporter json
=> Update version and dashboard for the monitor (#776)

scripts/tikv_details.json
Cherry pick https://github.com/pingcap/tidb-ansible/pull/790
=> Cherry pick #790 to release-3.0

scripts/tikv_details.json
=> tikv_details: add monitor_membership_change duration

roles/tikv/templates/tikv.toml.j2
cherry-pick from https://github.com/pingcap/tidb-ansible/pull/793
=> Fix tikv.toml.j2 (#793)

scripts/tidb.json
=> scrips: add parse & compile duration to tidb grafana

scripts/tidb.json
Cherry pick https://github.com/pingcap/tidb-ansible/pull/795
=> scrips: add parse & compile duration to tidb grafana (#795)

roles/drainer_cluster/defaults/main.yml, roles/drainer_cluster/templates/run_drainer_binary.sh.j2, roles/drainer_kafka/defaults/main.yml, roles/drainer_kafka/templates/run_drainer_binary.sh.j2, roles/pump_cluster/defaults/main.yml, roles/pump_cluster/templates/run_pump_binary.sh.j2, roles/pump_cluster/templates/run_pump_docker.sh.j2, roles/pump_kafka/defaults/main.yml, roles/pump_kafka/templates/run_pump_binary.sh.j2, roles/pump_kafka/templates/run_pump_docker.sh.j2
=> Add stderr log for pump/drainer

scripts/disk_performance.json
=> Update disk dashboard

roles/drainer_cluster/defaults/main.yml, roles/drainer_cluster/templates/run_drainer_binary.sh.j2, roles/drainer_kafka/defaults/main.yml, roles/drainer_kafka/templates/run_drainer_binary.sh.j2, roles/pump_cluster/defaults/main.yml, roles/pump_cluster/templates/run_pump_binary.sh.j2, roles/pump_cluster/templates/run_pump_docker.sh.j2, roles/pump_kafka/defaults/main.yml, roles/pump_kafka/templates/run_pump_binary.sh.j2, roles/pump_kafka/templates/run_pump_docker.sh.j2
=> Add stderr log for pump/drainer (#783)

roles/check_system_static/tasks/main.yml
* Add jmespath and jinja2 precheck
=> Add jmespath and jinja2 precheck (#802)

conf/pd.yml, roles/pd/vars/default.yml
This PR updates some PD configurations.
=> *: update pd parameters

scripts/tikv_details.json, scripts/tikv_summary.json, scripts/tikv_trouble_shooting.json
=> scripts: fix metrics to adapt new version of node exporter

scripts/tikv_details.json, scripts/tikv_summary.json, scripts/tikv_trouble_shooting.json
=> scripts: fix metrics to adapt new version of node exporter (#819)

scripts/disk_performance.json, scripts/pd.json
* *: update pd metrics
Signed-off-by: nolouch <nolouch@gmail.com>
=> [cherry-pick ]*: update pd metrics (#771)

scripts/tikv_details.json
=> Update titan metrics

roles/prometheus/templates/prometheus.yml.j2
See this [issue](https://github.com/pingcap/tidb-ansible/issues/825)
=> fix wrong format config file

roles/prometheus/templates/prometheus.yml.j2
* fix wrong format config file
=> fix wrong format config file (#829)

ansible.cfg, callback_plugins/help.py, callback_plugins/yaml.py
=> Error formatting output

callback_plugins/help.py, roles/check_config_static/tasks/main.yml
=> Fix the format for ansible error message

scripts/tidb.json
Cherry-pick to release 3.0.
No conflicts.
=> scripts: add some metrics for tidb (#830)

migrate_monitor.yml, rolling_update_monitor.yml, scripts/grafana-config-copy.py, scripts/tidb.json, scripts/tidb_summary.json, start.yml
No conflict cherry-pick to release 3.0.
=> script: add a new tidb summary dashboard (#852)

roles/prometheus/files/node.rules.yml
=> update node_exporter alert rules

roles/local/tasks/binary_deployment.yml, roles/local/templates/binary_packages.yml.j2, roles/tispark/tasks/main.yml
update tispark to new release 2.1.2
=> update tispark to new release 2.1.2 for release-3.0

roles/local/tasks/binary_deployment.yml, roles/local/templates/binary_packages.yml.j2, roles/tispark/tasks/main.yml
update tispark to new release 2.1.2
=> update tispark to new release 2.1.2 for release-2.1

roles/local/tasks/binary_deployment.yml, roles/local/templates/binary_packages.yml.j2, roles/tispark/tasks/main.yml
update tispark to new release 2.1.2
=> update tispark to new release 2.1.2 for release-2.0

scripts/binlog.json, scripts/blackbox_exporter.json, scripts/disk_performance.json, scripts/kafka.json, scripts/node.json, scripts/overview.json, scripts/pd.json, scripts/tidb.json, scripts/tidb_summary.json, scripts/tikv_details.json, scripts/tikv_summary.json, scripts/tikv_trouble_shooting.json
=> update dashboard json

roles/prometheus/files/tikv.accelerate.rules.yml, roles/prometheus/tasks/main.yml, roles/prometheus/templates/prometheus.yml.j2
Add recording rules to the top 25 most slow quries in tikv page.
=> prometheus: add recording rules to speed up tikv panel

scripts/tikv_details.json
Signed-off-by: 5kbpers <tangminghua@pingcap.com>
Add a counter of the total executed requests number.
=> tikv: optimize metrics of local reader

scripts/tikv_details.json
Signed-off-by: 5kbpers <tangminghua@pingcap.com>
cherry-pick https://github.com/pingcap/tidb-ansible/pull/873
=> Cherry-pick: optimize metrics of local reader

scripts/overview.json
=> update tikv monitor on overview dashboard

scripts/tidb.json, scripts/tidb_summary.json
cherry-pick #882 to release 3.0
=> script: uniform interval factor and steppedLine in tidb_summary (#882)

common_tasks/get_pd_name.yml
=> Fix bug for rolling update pd

roles/prometheus/files/tikv.rules.yml
@overvenus @superlzs0476 @LinuxGit PTAL
=> fix alert rules

roles/local/templates/binary_packages.yml.j2, roles/tispark/tasks/main.yml
=> upgrade spark to 2.4.3

roles/local/templates/binary_packages.yml.j2, roles/tispark/tasks/main.yml
=> upgrade spark to 2.4.3(3.0)

roles/local/templates/binary_packages.yml.j2, roles/tispark/tasks/main.yml
=> upgrade spark to 2.4.3(2.1)

roles/local/tasks/binary_deployment.yml, roles/local/templates/binary_packages.yml.j2, roles/tispark/tasks/main.yml
release tispark-2.1.4 for branch release-3.0
=> release tispark-2.1.4 for branch release-3.0

roles/local/tasks/binary_deployment.yml, roles/local/templates/binary_packages.yml.j2, roles/tispark/tasks/main.yml
release tispark-2.1.4 for branch release-2.1
=> release tispark-2.1.4 for branch release-2.1

scripts/tikv_details.json
=> script/tikv: fix time unit

scripts/tikv_details.json
=> script/tikv: fix time unit (#922)

scripts/tikv_details.json, scripts/tikv_summary.json
Add description for grafana tikv dashboard.
This json file was generated by grafana.
=> Add description for tikv dashboard

roles/local/tasks/binary_deployment.yml, roles/local/templates/binary_packages.yml.j2, roles/tispark/tasks/main.yml
=> update tispark to 2.2.0 (release-3.0)

scripts/pd.json
Add description for grafana pd dashboard.
This json file was generated by grafana, and some fields like "scopedVars" was removed.
=> Add description for pd dashboard

conf/tidb.yml, roles/tidb/vars/default.yml
* Update tidb configuration
via https://github.com/pingcap/tidb/pull/12049
=> Update tidb configuration (#932)

scripts/pd.json
Currently, the release-2.1 branch has multiple namings for a store. This PR unifies the name of stores.
=> scripts: unify the name of stores

roles/node_exporter/templates/run_node_exporter_binary.sh.j2, scripts/node.json
* Add metrics to node_exporter
* Update roles/node_exporter/templates/run_node_exporter_binary.sh.j2
Co-Authored-By: sykp241095 <sykp241095@gmail.com>
=> Add metrics to node_exporter (#907)

roles/check_system_dynamic/tasks/main.yml
=> Update disk space check module (#937)

deploy.yml
=> Modify perf tools deploying path

scripts/tikv_trouble_shooting.json
=> Add disk metrics and multi-selection to tikv trouble shooting

.gitignore, scripts/tikv_trouble_shooting.json
Signed-off-by: qupeng <qupeng@pingcap.com>
=> improve trouble shooting dashboard

roles/prometheus/files/tidb.rules.yml
Signed-off-by: Lonng <heng@lonng.org>
Some metrics name changed.
1. https://github.com/pingcap/tidb/pull/5858
2. https://github.com/pingcap/tidb/pull/5863
=> fix TiDB alert rules

roles/prometheus/files/tidb.rules.yml
Signed-off-by: Lonng <heng@lonng.org>
Cherry-pick #960 for release-2.1
=> fix TiDB alert rules (#960)

scripts/overview.json
This PR fixes some PD metrics in the overview dashboard to keep consistent with the PD dashboard.
=> scripts: fix some metrics in overview dashboard

scripts/pd.json
This PR can be merged after pingcap/pd#1746
=> scripts: support act on for filter metrics

scripts/performance_read.json, scripts/performance_write.json
Signed-off-by: lucklove <gnu.crazier@gmail.com>
=> script: integrate performance map

callback_plugins/help.py
=> Update error format

migrate_monitor.yml, rolling_update_monitor.yml, scripts/grafana-config-copy.py, scripts/performance_read.json, scripts/performance_write.json, start.yml
Signed-off-by: lucklove <gnu.crazier@gmail.com>
=> deploy performance map on grafana

rolling_update.yml, start.yml
=> Add port check for tidb/tikv

roles/check_config/tasks/check_pd_config.yml, roles/check_config/tasks/check_tidb_config.yml, roles/check_config/tasks/check_tikv_config.yml
Fix the case of variable coverage after executed config check.
@sykp241095 PTAL
=> Update config check

roles/check_config/tasks/check_pd_config.yml, roles/check_config/tasks/check_tidb_config.yml, roles/check_config/tasks/check_tikv_config.yml, roles/check_system_dynamic/tasks/main.yml
=> update config check 3.0

roles/check_config_static/tasks/main.yml, scripts/inventory_check.py
@sykp241095 PTAL
**For example:**
=> Add inventory check function

scripts/tidb.json
cherry-pick https://github.com/pingcap/tidb-ansible/pull/976
=> tidb: add index speed metric (#976)

scripts/performance_read.json, scripts/performance_write.json
Signed-off-by: lucklove <gnu.crazier@gmail.com>
=> bugfix: fix performance map grpc thread cpu usage

roles/prometheus/files/tikv.rules.yml, scripts/overview.json
Signed-off-by: Breezewish <me@breeswish.org>
Cherry pick https://github.com/pingcap/tidb-ansible/pull/990
=> Cherry pick: Fix overview metrics (#990)

scripts/tikv_details.json
Signed-off-by: Little-Wallace <bupt2013211450@gmail.com>
- Add metric to show which reason cause write stall
- Add metric to show scheduler writing bytes.
=> add metric for write stall and scheduler writing bytes

roles/prometheus/files/tikv.rules.yml
Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>
Cherry-picks #994 to release-3.0.
=> Update alert rule to work properly when distrubuted gc is enabled (#994)

conf/tidb.yml, roles/tidb/vars/default.yml
Signed-off-by: tabokie <xy.tao@outlook.com>
=> remove obsolete config pessimistic txn ttl

scripts/tikv_details.json
Signed-off-by: tabokie <xy.tao@outlook.com>
=> add metrics for batch request

conf/tikv.yml, roles/tikv/templates/tikv.toml.j2, roles/tikv/vars/default.yml
=> config: add gc config

conf/tikv.yml, roles/tikv/templates/tikv.toml.j2, roles/tikv/vars/default.yml
Cherry pick #1018. https://github.com/tikv/tikv/pull/5735
=> config: add gc config (#1018)

scripts/tikv_details.json
=> tikv: add backup metrics

scripts/tikv_details.json
=> tikv: add backup metrics (#1031)

scripts/tidb.json, scripts/tidb_summary.json
=> scripts: update TiDB transaction counter

scripts/pd.json
It can be merged after https://github.com/pingcap/pd/pull/1888
=> add metrics for op influence and tolerant resource

scripts/tidb.json, scripts/tidb_summary.json
=> scripts: update TiDB transaction counter (#1032)

scripts/tikv_details.json
Fix backup thread CPU usage by correct thread name.
=> tikv: fix backup thread CPU usage

scripts/pd.json
cherry-pick #966 to release-3.0
=> scripts: support act on for filter metrics (#966)

scripts/overview.json, scripts/pd.json
This PR removes the namespace since pingcap/pd#1804 is merged.
=> scripts: remove namespace

unsafe_cleanup.yml, unsafe_cleanup_data.yml
@sykp241095 @superlzs0476 PTAL
=> add confirm when run cleanup operation

roles/local/templates/binary_packages.yml.j2, roles/local/templates/common_packages.yml.j2
=> add sha256sum check

roles/local/templates/binary_packages.yml.j2
=> remove extra checksum

scripts/overview.json, scripts/pd.json
This PR fixes the PD role metrics
=> scripts: fix PD role metrics

conf/pd.yml, conf/tidb.yml, conf/tikv.yml, roles/pd/vars/default.yml, roles/tidb/vars/default.yml, roles/tikv/vars/default.yml
=> revert config 3.0

rolling_update.yml
Fix error when `tidb` version number format is `3.0.6`.
=> update version check

roles/local/tasks/binary_deployment.yml, roles/local/templates/binary_packages.yml.j2, roles/tispark/tasks/main.yml
release tispark-2.1.7 for release-2.1 branch
=> release tispark-2.1.7 for release-2.1 branch

roles/local/tasks/binary_deployment.yml, roles/local/templates/binary_packages.yml.j2, roles/tispark/tasks/main.yml
release tispark-2.1.7 for release-3.1 branch
=> release tispark-2.1.7 for release-3.1 branch

roles/local/tasks/binary_deployment.yml, roles/local/templates/binary_packages.yml.j2, roles/tispark/tasks/main.yml
=> release tispark-2.1.7 for release-3.0 branch

scripts/pd.json
=> fix pd role metric for 3.0

scripts/tikv_details.json
=> tikv_details: speed up grafana display - release-3.0

scripts/tikv_details.json
=> tikv_details: speed up grafana display - release-3.1

conf/tikv.yml, roles/tikv/vars/default.yml
See https://github.com/tikv/tikv/pull/6244
=> tikv/conf: change default pessimistic-txn.wake-up-delay-duration

roles/bootstrap/tasks/root_tasks.yml
@ethercflow @zhouqiang-cl  PTAL
=> THP: set disable

scripts/tidb.json
http://172.16.5.73:23335/d/000000011/rnew_3_0-tidb?orgId=1&from=now-30m&to=now&refresh=5s
add a panel for lock keys duration
=> server: add lock duration panel

roles/bootstrap/tasks/root_tasks.yml
=> THP: set disable (#1079)

migrate_monitor.yml, rolling_update_monitor.yml, scripts/br.json, scripts/grafana-config-copy.py, start.yml
cherry pick #1091 to release-3.1
=> scripts:add backup & restore dashboard (#1091)

scripts/tidb.json
See http://172.16.5.34:34125/d/000000011/test-cluster-tidb?orgId=1
=> scripts: update transaction TTL related metrics for  tidb grafana

conf/tidb.yml, roles/tidb/templates/tidb.toml.j2, roles/tidb/vars/default.yml
This PR add support for the coprocessor cache configurations.
Signed-off-by: Breezewish <me@breeswish.org>
=> Add copr cache related configurations

conf/tidb.yml, roles/tidb/templates/tidb.toml.j2, roles/tidb/vars/default.yml
To align with https://github.com/pingcap/tidb/pull/14373
=> Hide Coprocessor Cache Configurations

conf/tikv.yml, roles/tikv/vars/default.yml
See https://github.com/tikv/tikv/pull/6426
=> tikv-conf: update default pessimistic-txn config

scripts/tikv_details.json
Update metrics about lock manager:
=> scripts: more metrics for lock manager

conf/tikv.yml, roles/tikv/vars/default.yml
=> tikv-conf: update default pessimistic-txn config (#1101)

scripts/tikv_details.json
=> scripts: more metrics for lock manager (#1090)

conf/tikv.yml, roles/tikv/vars/default.yml
Signed-off-by: Little-Wallace <bupt2013211450@gmail.com>
=> change tikv config template

common_tasks/transfer_pd_leader.yml
* fix get current pd leader error when rolling update pd
=> fix get current pd leader error when rolling update pd (#1081)

roles/tiflash/templates/run_tiflash_binary.sh.j2
cherry-pick https://github.com/pingcap/tidb-ansible/pull/1128
=> [cherry-pick] rename theflash

scripts/tidb.json
=> scripts: add deadlock duration metrics

scripts/node.json
=> Update wrong expression in node.json

scripts/tidb.json
tidb change: https://github.com/pingcap/tidb/pull/14634
http://172.16.5.73:23335/d/000000011/rnew_3_0-tidb?orgId=1&from=1580871784284&to=1580872094286
=> add lock keys counter panel in tidb transaction tab

conf/tiflash-learner.yml, conf/tiflash.yml, roles/tiflash/defaults/main.yml, roles/tiflash/tasks/main.yml, roles/tiflash/templates/tiflash.toml.j2, roles/tiflash/templates/tiflash_learner.toml.j2, roles/tiflash/vars/tiflash-learner.yml, roles/tiflash/vars/tiflash.yml
https://docs.google.com/document/d/1whGPc5t48hTfIzwXz1LumkVHwYlazeFIKiwk_neZJOE/edit?usp=sharing
=> refactor tiflash config

conf/tiflash-learner.yml, conf/tiflash.yml, roles/tiflash/defaults/main.yml, roles/tiflash/tasks/main.yml, roles/tiflash/templates/tiflash.toml.j2, roles/tiflash/templates/tiflash_learner.toml.j2, roles/tiflash/vars/tiflash-learner.yml, roles/tiflash/vars/tiflash.yml
cherry-pick https://github.com/pingcap/tidb-ansible/pull/1136
=> [cherry-pick] refactor tiflash config

roles/check_config_static/tasks/main.yml, roles/grafana/templates/data_source.json.j2, roles/prometheus/templates/prometheus.yml.j2, rolling_update_monitor.yml, scripts/grafana-config-copy.py, start.yml
=> Support multiple monitor nodes

group_vars/tiflash_servers.yml, roles/tiflash/defaults/main.yml, roles/tiflash/tasks/main.yml, roles/tiflash/templates/tiflash_learner.toml.j2
open proxy metrics port for prometheus to pull
=> add tiflash proxy status port config

roles/check_config_static/tasks/main.yml, roles/grafana/templates/data_source.json.j2, roles/prometheus/templates/prometheus.yml.j2, rolling_update_monitor.yml, scripts/grafana-config-copy.py, start.yml
* Support multiple monitor nodes
=> Support multiple monitor nodes (#1137)

conf/tiflash.yml, group_vars/tiflash_servers.yml, roles/tiflash/defaults/main.yml, roles/tiflash/tasks/main.yml, roles/tiflash/templates/tiflash.toml.j2, roles/tiflash/vars/tiflash.yml
cherry pick https://github.com/pingcap/tidb-ansible/pull/1144
=> [cherry-pick] tiflash add metrics port (#1144)

roles/prometheus/templates/prometheus.yml.j2
* add tiflash conf in prometheus for tiflash dashboard
=> add tiflash conf in prometheus for tiflash dashboard (#1146)

excessive_rolling_update.yml, roles/pd/templates/pd.toml.j2, rolling_update.yml, rolling_update_monitor.yml, scripts/grafana-config-copy.py, scripts/tiflash_proxy_summary.json, scripts/tiflash_summary.json, start.yml
Add TiFlash dashboard
http://172.16.5.149:3000/d/SVbh2xUWk/test-cluster-tiflash-summary?orgId=1
http://172.16.5.149:3000/d/myoLjZQWz/test-cluster-tiflash-proxy-summary
@marsishandsome PTAL
=> Add tiflash dashboard

excessive_rolling_update.yml, roles/pd/templates/pd.toml.j2, rolling_update.yml, rolling_update_monitor.yml, scripts/grafana-config-copy.py, scripts/tiflash_proxy_summary.json, scripts/tiflash_summary.json, start.yml
* Add tiflash dashboard
* update tiflash_summary
via #1151 
@marsishandsome PTAL
=> Add tiflash dashboard (#1150)

roles/tiflash/templates/tiflash_learner.toml.j2
related PR: https://github.com/pingcap/tics/pull/467
=> remove tiflash_http_port config

roles/tiflash/templates/tiflash_learner.toml.j2
cherry pick: https://github.com/pingcap/tidb-ansible/pull/1153
=> [cherry-pick] remove tiflash_http_port config (#1153)

scripts/tikv_details.json
=> scripts: more metrics for lock manager (#1090) (#1114)

roles/prometheus/files/tiflash.rules.yml, roles/prometheus/tasks/main.yml, roles/prometheus/templates/prometheus.yml.j2, scripts/tiflash_proxy_summary.json, scripts/tiflash_summary.json
cherry pick: https://github.com/pingcap/tidb-ansible/pull/1158
=> add tiflash alert rules & refactor tiflash grafana dashboard (#1158)

conf/tikv.yml, roles/tikv/templates/tikv.toml.j2, roles/tikv/vars/default.yml, scripts/tikv_details.json, scripts/tikv_trouble_shooting.json
Signed-off-by: Yilin Chen <sticnarf@gmail.com>
This PR adds configuration and grafana pannels for unified read pool (which is introduced in TiKV 4.0).
=> support unified read pool

roles/check_system_dynamic/tasks/main.yml, roles/check_system_static/tasks/main.yml, roles/tikv/tasks/check_filesystem.yml
=> fix 404 url

roles/check_system_dynamic/tasks/main.yml, roles/check_system_static/tasks/main.yml, roles/tikv/tasks/check_filesystem.yml
via #1163 
* fix 404 url
* update ntp check url
=> fix 404 url (#1163)

start.yml
=> fix error when wait replication

start.yml
=> fix error when wait replication (#1166)

inventory.ini
cherry pick: https://github.com/pingcap/tidb-ansible/pull/1176
=> add tiflash comment (#1176)

conf/tikv.yml, roles/tikv/templates/tikv.toml.j2, roles/tikv/vars/default.yml, scripts/tikv_details.json, scripts/tikv_trouble_shooting.json
Signed-off-by: Yilin Chen <sticnarf@gmail.com>
@sticnarf PTAL
=> support unified read pool (#1112)

create_users.yml
Modify create_users.yml to make it more friendly to mac users.
=> Modify create_users.yml. (#1041)

roles/grafana/templates/data_source.json.j2
It will cause the deployment to fail.
=> multiple monitor: fix deploy error

conf/tidb.yml, roles/tidb/vars/default.yml
via #https://github.com/pingcap/tidb/pull/15012
=> TiDB: add a variable to control the max index length

roles/check_config_static/tasks/main.yml, roles/grafana/templates/data_source.json.j2, roles/prometheus/templates/prometheus.yml.j2, rolling_update_monitor.yml, scripts/grafana-config-copy.py, start.yml
=> support multiple monitor node

scripts/tikv_details.json
UCP [#5751](https://github.com/tikv/tikv/issues/6541)
add tikv_engine_write_wal_time_micro_seconds metric
=> add tikv_engine_write_wal_time_micro_seconds metric

conf/tidb.yml, roles/tidb/vars/default.yml
=> conf, roles: add the config of alter-primary-key

conf/tidb.yml, roles/tidb/vars/default.yml
=> conf, roles: add the config of alter-primary-key (#1209)

conf/tidb.yml, roles/tidb/vars/default.yml
=> conf, roles: add the config of alter-primary-key(#1209)

conf/tiflash.yml, roles/tiflash/vars/tiflash.yml
cherry pick https://github.com/pingcap/tidb-ansible/pull/1222
=> update tiflash storage engine (#1222)

conf/tidb.yml, roles/tidb/templates/tidb.toml.j2, roles/tidb/vars/default.yml
Refer to https://github.com/pingcap/tidb/pull/14734, https://github.com/pingcap/tidb/pull/15259 and https://github.com/pingcap/tidb/pull/13127
=> conf, roles: add the config of auto-random, expression and new-collation

roles/check_system_static/tasks/main.yml, scripts/check/epoll_chk.cc
Reminder user to upgrade kernel when epollex check fails.
=> Add epollex check reminder

scripts/tiflash_summary.json
related PR: https://github.com/pingcap/tics/pull/540
=> add tiflash metrics tiflash_storage_write_amplification

scripts/tiflash_summary.json
cherry pick https://github.com/pingcap/tidb-ansible/pull/1233
=> add tiflash metrics tiflash_storage_write_amplification (#1233)

deploy.yml, excessive_rolling_update.yml, roles/dashboard_topo/tasks/main.yml, rolling_update.yml, start.yml
=> update dashboard init (#1226)

conf/tidb.yml, roles/tidb/vars/default.yml
=> config, roles: add config of server-version  (#1231)

conf/tidb.yml, roles/tidb/vars/default.yml
=> config, roles: add config of server-version (#1231)

conf/tikv.yml, roles/tikv/vars/default.yml
Signed-off-by: ssebo <ssebo.zzz@gmail.com>
=> conf: wait-for-lock-timeout and wake-up-delay-duration readable

conf/tidb.yml, roles/tidb/templates/tidb.toml.j2, roles/tidb/vars/default.yml
Refer to pingcap/tidb#14734, pingcap/tidb#15259 and pingcap/tidb#13127
=> conf, roles: add the config of auto-random, expression and new-collation(#1217) 

conf/tidb.yml, roles/tidb/templates/tidb.toml.j2, roles/tidb/vars/default.yml
=> conf, roles: add the config of auto-random (#1217)

conf/tikv.yml, roles/tikv/vars/default.yml
=> cherry pick sync unified read pool default configurations with tikv#7234 (#1232)

scripts/blackbox_exporter.json, scripts/overview.json
cherry pick https://github.com/pingcap/tidb-ansible/pull/1255
=> update tiflash grafana (#1255)

group_vars/tiflash_servers.yml
cherry pick https://github.com/pingcap/tidb-ansible/pull/1264
=> delete interserver_http_port (#1264)

scripts/tiflash_summary.json
=> Show TiFlash storage metrics in grafana (#1278)

conf/tikv.yml, roles/tikv/vars/default.yml
Signed-off-by: ssebo <ssebo.zzz@gmail.com>
Should be taken into v4.0.0-rc.1
=> conf: wait-for-lock-timeout and wake-up-delay-duration readable (#1216)

scripts/tiflash_summary.json
https://github.com/pingcap/tics/pull/688
=> TiFlash Grafana: Read Index Count -> Read Index Rate

scripts/tiflash_summary.json
cherry pick https://github.com/pingcap/tidb-ansible/pull/1291
=> TiFlash Grafana: Read Index Count -> Read Index Rate (#1291)

roles/local/tasks/binary_deployment.yml, roles/local/templates/binary_packages.yml.j2, roles/tispark/tasks/main.yml
cherry pick https://github.com/pingcap/tidb-ansible/pull/1294
=> update tispark to 2.1.9 (#1294)

conf/tikv.yml, roles/tikv/templates/tikv.toml.j2, roles/tikv/vars/default.yml
Signed-off-by: Yi Wu <yiwu@pingcap.com>
=> update tikv config template for security features

conf/tikv.yml, roles/tikv/templates/tikv.toml.j2, roles/tikv/vars/default.yml
Signed-off-by: Yi Wu <yiwu@pingcap.com>
=> update tikv config template for security features (#1298)

scripts/tidb.json
The data source name is incorrect for these two panels in release-3.0
=> fix panel datasource name

conf/pd.yml, conf/tidb.yml, roles/pd/templates/pd.toml.j2, roles/pd/vars/default.yml, roles/tidb/vars/default.yml
=> Add telemetry and dashboard configurations

conf/pd.yml, conf/tidb.yml, roles/pd/templates/pd.toml.j2, roles/pd/vars/default.yml, roles/tidb/vars/default.yml
Cherry pick https://github.com/pingcap/tidb-ansible/pull/1319 to release-4.0
=> cherry pick: Add telemetry and dashboard configurations (#1319)

conf/pd.yml, roles/pd/vars/default.yml
=> update pd config

scripts/tikv_details.json
Signed-off-by: Xintao <hunterlxt@live.com>
=> Add perf context panel for tikv grafana template

scripts/tiflash_summary.json
=> Added some panels for TiFlash about write stall

scripts/tiflash_proxy_details.json
=> add tiflash encryption metrics

scripts/tiflash_summary.json
Signed-off-by: JaySon-Huang <tshent@qq.com>
Preview URL: http://172.16.5.85:21510/d/CLd9JXDGz/test-cluster-tiflash-summary___new?orgId=1&from=1599632595231&to=1599633866293
=> Add metrics for ApplySnapshot and IngestSST in TiFlash

scripts/table-regions.py
Signed-off-by: JaySon-Huang <tshent@qq.com>
For partition tables, we should sum the regions' distribution of all partitions.
=> Fix table-regions.py for partition table

roles/node_exporter/templates/run_node_exporter_binary.sh.j2
As requested in https://github.com/pingcap/tiup/issues/877
=> node_exporter: enable collector.buddyinfo
