bootstrap.yml
inventory.ini
roles/machine_benchmark/defaults/main.yml
roles/machine_benchmark/tasks/main.yml

- Benchmark the write speed of tikv deploy_dir disk with dd command(`dd bs=4k count=250000 oflag=direct if=/dev/zero of={{ deploy_dir }}/io_test.txt`,  add the oflag parameter to bypass the disk page cache)
- fail if speed less than min_write_speed
- add `machine_benchmark = True`  in the inventory.ini

bootstrap: benchmark the write speed of tikv disk

---

group_vars/all.yml
group_vars/monitored_servers.yml
group_vars/monitoring_servers.yml
roles/node_exporter/defaults/main.yml
roles/pd/tasks/main.yml

- Fix: prometheus.yml.j2 task can't obtain node_exporter_port  attribute when deploying prometheus on separate server.
- Fix typo.

fix no attribute 'node_exporter_port'

---

roles/machine_benchmark/tasks/main.yml

When using awk to filter the result of dd command, FS is different between LANG='en_US.UTF-8' and LANG='zh_CN.UTF-8'. Set LANG env for it.

bootstrap: add dd command LANG

---

roles/tikv/templates/run_tikv.sh.j2

If TZ is not set, tikv will stat(/etc/localtime) twice every logging operation.

roles/tikv: add TZ setting before start tikv

---

roles/local/templates/binary_packages.yml.j2

The old download link for tispark jar should be replaced.
@LinuxGit  @xuechunL PTAL.

update tispark jar address

---

scripts/grafana-config-copy.py

The `scripts/grafana-config-copy.py` script is executed on the Control Machine and is written in python2. However, not all Linux distributions use python2 by default (such as Arch Linux), and thus wrongly pick python3 for the script.
With this fix, I can successfully provision TiDB with Arch Linux on the Control Machine (the other machines still used CentOS).

scripts: Ensure the interpreter is python2

---

conf/tikv.yml
roles/tikv/templates/tikv.toml.j2
roles/tikv/vars/default.yml

We will have coprocessor read pool soon, so that config of these two need to be separated.
Related TiKV PR: https://github.com/pingcap/tikv/pull/2813

readpool -> readpool.storage

---

scripts/tidb.json

Update metrics according to https://github.com/pingcap/tidb/pull/6278
PTAL @zz-jason  @LinuxGit

scripts: add metrics for dynamic update

---

scripts/tidb.json

Those query errors would return to client, when we find them in the grafana panel, we should check the log to see details.
And we'll should also add alert rules for them.
@coocood @shenli

script: update grafana add a "failed query" panel

---

scripts/tikv.json

1. There are two duplicated "server_is_busy" panel, removed one.
2. This panel does not display which channel is full, fixed.

Optimize channel full metrics

---

scripts/table-regions.py

Add a python script **table-regions.py** to calculate the region leader distribution of a table in TiDB.
1. To quickly identify whether a table or index has **only one** region
2. To quickly identify whether the leader distribution of table or index is balanced among all the tikv servers
```sh
➜ ./scripts/table-regions.py -h
usage: table-regions.py [-h] [--host HOST] [--port PORT] database table
Show leader distribution of a TiDB table.
positional arguments:
database     database name
table        table name
optional arguments:
-h, --help   show this help message and exit
--host HOST  tidb-server address, default: 127.0.0.1
--port PORT  tidb-server status port, default: 10080
```
```sh
➜ ./scripts/table-regions.py --host 172.16.10.16 tpch10 lineitem
region leader distribution for table …
```

add a python script to show the leader distribution of a table

---

scripts/tidb.json

See in grafana batch add index dosen't work,because the configuration name is inconsistent.

metrics:*ddl change grafana config

---

conf/tikv.yml
roles/tikv/vars/default.yml

1. `max-tasks-xxx` is deprecated, `max-tasks-per-worker-xxx` is introduced.
2. `end-point-max-tasks` is deprecated, it will be inferred from `max-tasks-per-worker-xxx`.
~~Please merge this PR after https://github.com/pingcap/tikv/pull/3093 is merged.~~

TiKV max-tasks-per-worker-xxx config

---

scripts/pd.json

- use `decbytes` instead of `bytes` (GiB -> GB)
- round heartbeat latency (show 0 for latency less than 1s)
- fix wrong peer round trip query

script: update pd grafana template

---

create_grafana_api_keys.yml

grafana:
When you put `tidb-ansible` in `/root`,  "Permission denied" error will occur when running "Check grafana API Key file existed" task. This pr will fix it. BTW. It's recommended to put `tidb-ansible` in `/home/tidb`.

grafana: fix grafana key permission error

---

scripts/grafana_pdf.py

There are 3 arguments that can be used:
- `-t`/`--time`: A relative time range, collect the data from latest period, e.g: `-t 2h`, `--time 5h`
- `--time-from`: The start time when specifying an absolute time period, e.g: `--time-from "2018-06-27 01:00:00"`, `--time-from "17:00"`, `--time-from "6-27"`
- `--time-to`: The end time when specifying an absolute time period, in the same format as `--time-from`
It's possible to mix formats of `--time-from` and `--time-to`, if no argument specified, a default time period of latest 3 hours is used.
- Support both Python 2 & 3
- Add simple exception handling when querying Grafana APIs
- Format code with `autopep8`

Grafana screenshot with time range

---

conf/tidb.yml
roles/tidb/vars/default.yml

Since enabling local latches for the transaction may cause fake conflicts in some situations, we'd like to disable it in default config.
@coocood @LinuxGit PTAL
The related PR: https://github.com/pingcap/tidb-ansible/pull/433

config: disable local latches for txn in tidb

---

scripts/tikv.json

In PR https://github.com/pingcap/tikv/pull/3119 , GC logic is moved out of scheduler, and metrics are also updated.
This PR updates Grafana dashboard of TiKV to follow these changes.
This PR should be merged after merging https://github.com/pingcap/tikv/pull/3119 .

tikv: Update grafana dashboard to use new GC metrics 

---

roles/collect_diagnosis/tasks/main.yml
roles/collector_pd/tasks/collect_config.yml
roles/collector_pd/tasks/collect_log.yml
roles/collector_pd/tasks/main.yml
roles/collector_tidb/tasks/collect_config.yml
roles/collector_tidb/tasks/collect_log.yml
roles/collector_tidb/tasks/main.yml
roles/collector_tikv/tasks/collect_config.yml
roles/collector_tikv/tasks/collect_log.yml
roles/collector_tikv/tasks/main.yml
roles/local/templates/common_packages.yml.j2

Several changes are made in this PR:
- Do not compress output files until all collecting tasks are done
- Compress and retrieve tarball only once per role
- Add tasks to collect config files of TiDB/TiKV/PD instances
This PR, in combination with #453, setup the basic structure of `tidb-insight` tasks, and future new tasks would (hopefully) be easier to be added.

Collect config files with Insight

---

roles/collect_diagnosis/tasks/main.yml
roles/collector_pd/tasks/main.yml
roles/collector_tidb/tasks/main.yml
roles/collector_tikv/tasks/main.yml
roles/local/tasks/main.yml
roles/local/templates/common_packages.yml.j2

- Add collecting of basic system information with `collector`
- If multiple instances are deployed on one server, the last one run `collector` will overwrite former results
- Add collecting of PD API info on pd instances
- If multiple instances are deployed on one server, the output will be distinguished by hostname and listening port
- Change download `tidb-insight` tarball name, remove the version number from it

Add collecting of basic system info & pd info

---

collect_diagnosis.yml
roles/collector_pd/tasks/collect_config.yml
roles/collector_pd/tasks/collect_log.yml
roles/collector_pd/tasks/main.yml
roles/collector_prometheus/tasks/main.yml
roles/collector_tidb/tasks/collect_config.yml
roles/collector_tidb/tasks/collect_log.yml
roles/collector_tidb/tasks/main.yml
roles/collector_tikv/tasks/collect_config.yml
roles/collector_tikv/tasks/collect_log.yml
roles/collector_tikv/tasks/main.yml
roles/local/templates/common_packages.yml.j2

* Update to `tidb-insight`'s new sub-command strategy
* Add exporting of Prometheus metrics, which can be them used for offline analysis

Update to latest tidb-insight, add feature to dump Prometheus metrics

---

roles/collector_tidb/tasks/main.yml
roles/local/templates/common_packages.yml.j2

Collects TiDB server info from the TiDB server info API.
Note: This feature does not work on TiDB versions prior to v2.1 and will get empty result.

tidb-insight: add support of collecting of TiDB server info

---

roles/prometheus/files/tikv.rules.yml
scripts/tikv.json

alert approximate region size too large when maximum size continually exceed 1GB in one minute.

tikv: add large region alert

---

scripts/check/parse_fio_output.py

parse_fio_output.py parses fio JSON output, used to check disk performance.
```
./parse_fio_output.py -h
usage: parse_fio_output.py [-h] [--read-iops] [--read-lat] [--write-iops]
[--write-lat] [--target TARGET] [--summary]
Parse fio output.
optional arguments:
-h, --help       show this help message and exit
--read-iops      fio read IOPS.
--read-lat       fio read average latency. (ns)
--write-iops     fio write IOPS.
--write-lat      fio write average latency. (ns)
--target TARGET  file path of fio JSON output.
--summary        fio output summary.
```
Example:
```
./parse_fio_output.py --target="fio_randr_w_result.json" --summary
jobname: fio mixed randread and sequential write test
read: IOPS=12502
lat (ns): min=2950, max=19963310, avg=182391
clat percentiles (ns): 95.00th=378880, …
```

check: add parse_fio_output.py

---

roles/prometheus/files/pd.rules.yml

This PR is related to pingcap/pd#1173.

pd: alert time fallback

---

roles/check_system_static/tasks/main.yml

Fail task when Linux kernel vm.overcommit_memory parameter is set to 2.

check: Linux kernel vm.overcommit_memory parameter

---

roles/local/templates/common_packages.yml.j2

Fixed download URL link for TiDB binary release.

fix tidb download url

---

scripts/tidb.json

Add job action and schema version information to DDL metrics.
Merge after pingcap/tidb#7472

scripts: update DDL metrics

---

scripts/tikv.json

Metrics of TiKV has changed in this PR:
https://github.com/tikv/tikv/pull/3529
This PR is to monitor the new metrics of it.
(Also note that https://github.com/tikv/tikv/pull/3529 is included in tikv 2.1 rc2)

Update tikv dashboard to monitor new metrics for gc and destroy range

---

conf/tidb.yml
roles/tidb/vars/default.yml

As the title says, TiDB adds a new configuration called "force-priority".
PTAL @LinuxGit

conf: add tidb force priority

---

roles/systemd/templates/systemd_binary.service.j2

Add limits on the unit's memory consumption, It's optional.
example:
```
[tidb_servers]
tidb1 ansible_host=172.16.10.72 MemoryLimit=2G
```
MemoryLimit=value
Replace value with a limit on maximum memory usage of the processes executed in the cgroup. Use suffixes K, M, G, or T to identify Kilobyte, Megabyte, Gigabyte, or Terabyte as the unit of measurement. Also, the MemoryAccounting parameter has to be enabled for the unit.
```
● tidb-4000.service - tidb-4000 service
Loaded: loaded (/etc/systemd/system/tidb-4000.service; disabled; vendor preset: disabled)
Active: active (running) since 日 2018-10-14 04:32:13 CST; 23s ago
Main PID: 27238 (tidb-server)
Memory: 25.9M (limit: 2.0G)
CGroup: /system.slice/tidb-4000.service
└─27238 /usr/bin/tidb-server -P 4000 --status=10080 …
```

systemd: add MemoryLimit setting

---

roles/machine_benchmark/tasks/fio_randread_write.yml
roles/machine_benchmark/tasks/fio_randread_write_latency.yml
roles/machine_benchmark/tasks/main.yml

"fio_randread_write.yml" split  is split into "fio_randread_write.yml" and "fio_randread_write_latency.yml"
@LinuxGit @liubo0127 PTAL

machine_benchmark: fix randread and sequential write benchmark for latency

---

roles/local/templates/common_packages.yml.j2

This `tidb-insight` package adds feature to collect system uptime and process start time for TiDB modules.
See https://github.com/pingcap/tidb-insight/pull/48 for details.

tidb-insight: add sytem uptime and process start time

---

scripts/overview.json

Change 3 `bytes` to `decbytes`:
- make `Storage Capacity` same as `PD`
- make `Current Storage Size` same as `PD`
- make `cf size` same as `TiKV`

grafana: fix inconsistent radix units

---

scripts/tikv.json

Based on [TiKV 3712](https://github.com/tikv/tikv/pull/3712). 
If `triggered_writes_slowdown` is 1, then rocksdb is currently slowing-down all writes to prevent creating too many Level 0 files as compaction seems not able to catch up the write request speed.
If `triggered_writes_stop` is 1, then rocksdb is currently blocking any writes to prevent creating more L0 files.
3 states `normal`, `delayed`, `stopped` of RocsDB are shown.

Add tikv_engine_stall_conditions_changed to metrics;

---

scripts/tidb.json

Add the SQL type for transaction counter to split the internal and general transactions.

script:[grafana] add the SQL type for transaction counter

---

conf/tidb.yml
roles/tidb/vars/default.yml

current ansible default value for latches is too big and cause huge memory usage..
we need set default value follow tidb's one ref https://github.com/pingcap/tidb/blob/2f2b47f511f8311907af26314196a82dd254caf4/config/config.go#L270
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb-ansible/600)

conf: set right default capacity value for tidb txn_local_latches

---

scripts/tikv.json

Some of the metrics about GC in TiKV's board actually comes from TiDB. However there is {job=~"$job"} filter on them, where the $job evaluates to be `tikv_[0-9]+`. Then TiDB was filtered out.
This PR tries to fix it by removing this filter from these query expressions.

scripts/tikv: Fix TiKV's board can't show some GC metrics from PD

---

conf/tikv.yml
roles/tikv/templates/tikv.toml.j2
roles/tikv/vars/default.yml

`Titan` section is third degree section, so we need to make `tikv.toml.j2` to support third degree section.

Support titan config section

---

roles/prometheus/files/pd.rules.yml

This PR is used to alert if there is no store to make replicas for a while.

pd: alert if there is no store to make replicas

---

scripts/tikv_pull.json

This PR does:
- adjust `raftstore thread CPU`
- remove `process tick duration per server`
- adjust `memory`
- adjust `leader count` and `region count`

adjust metrics for threaded raftstore

---

scripts/tikv_pull.json
scripts/tikv_push.json

This PR is going to fix the problem which the metrics of a single TiKV can't be displayed in Grafana for `release-2.1` branch.

scripts: fix the single TiKV metrics

---

.gitignore
scripts/tikv_pull.json

Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>
This PR adds a panel in TiKV dashboard to show the running status of AutoGC.
Also the GC Speed panel is moved to above the GC lifetime and GC interval panels so it looks better now(?)
By the way I added `.vscode` to gitignore.
I'm not sure if I should update only `tikv_pull.json`.

Add metrics for Auto GC status

---

scripts/tikv_pull.json

Add tikv jemalloc stats to Grafana. Depends on https://github.com/tikv/tikv/pull/4332.
Screenshot:

Add tikv jemalloc stats to Grafana

---

graceful_stop.yml
group_vars/alertmanager_servers.yml
roles/alertmanager/templates/run_alertmanager_binary.sh.j2
roles/alertmanager/templates/run_alertmanager_docker.sh.j2
roles/pd/tasks/supervise_deployment.yml
roles/pd/tasks/systemd_deployment.yml
rolling_update.yml
start.yml
stop.yml
unsafe_cleanup.yml
unsafe_cleanup_data.yml

- Put the port into the name of the pd service. This allows multiple pds to be deployed on the same machine.
- Make the mesh port (or cluster port) of alertmanager configurable. This allows multiple alertmanagers to be deployed on the same machine.

Make it possible to have two cluster running on the same machine

---

roles/systemd/templates/systemd_binary.service.j2

#563 added `MemoryLimit` to limit memory consumption. Here a `CPUQuota` setting is added to limit CPU usage, and `IOReadBandwidthMax` and `IOWriteBandwidthMax` settings are added to limit disk IO bandwidth.
These settings are all optional argument applyed to hosts, and have the same value syntax as documented in the `SYSTEMD.RESOURCE-CONTROL(5)` man page

Add more resource control settings

---

roles/local/tasks/main.yml
roles/local/templates/common_packages.yml.j2

Fix local roles downloads binlog bug

---

roles/check_system_static/tasks/main.yml

Update os version limit

---

roles/check_system_static/tasks/main.yml

Update os version limit (#732)

---

scripts/pd.json

scripts: add store back to metrics

---

excessive_rolling_update.yml
rolling_update.yml

In the detection phase of the rolling update, just check the tidb-server version, maybe it should be checked in parallel.

Pre check tidb-servers version in parallel

---

README.md

Fixes a broken link (the file was renamed yesterday for English). There are redirects for accessing docs via web, but not via Git.
Changed both docs and docs-cn, since docs-cn will rename the file soon.

Update Readme URL to documentation

---

scripts/table-regions.py

the output like:
```
[RECORD - sbtest1.sbtest1] - Leaders Distribution:
total leader count: 4
store: 10, num_leaders: 1, percentage: 25.00%
store: 8, num_leaders: 2, percentage: 50.00%
store: 5, num_leaders: 1, percentage: 25.00%
[RECORD - sbtest1.sbtest1] - Peers Distribution:
total peers count: 12
store: 10, num_peers: 3, percentage: 25.00%
store: 4, num_peers: 2, percentage: 16.67%
store: 6, num_peers: 1, percentage: 8.33%
store: 8, num_peers: 2, percentage: 16.67%
store: 1, num_peers: 2, percentage: 16.67%
store: 5, num_peers: 1, percentage: 8.33%
store: 9, num_peers: 1, percentage: 8.33%
[INDEX - k_1] - Leaders Distribution:
total leader count: 3
store: 6, num_leaders: 1, percentage: 33.33%
store: 7, num_leaders: 1, percentage: 33.33%
store: 10, num_leaders: 1, percentage: 33.33% …
```

scripts: add peers distribution of table regions

---

conf/drainer-cluster.toml
conf/drainer-kafka.toml
conf/pump-cluster.yml
group_vars/all.yml
inventory.ini
roles/pump_cluster/templates/pump.toml.j2
roles/pump_cluster/vars/default.yml

@superlzs0476 @WangXiangUSTC PTAL

Update drainer config

---

scripts/tidb.json

TiDB pannel use to only has 1 pannel for Duration.
In this PR, I add 4 type pannel so that we can see what kind of sql is slow.

tidb: add type duration panel

---

conf/pump-cluster.yml
roles/pump_cluster/vars/default.yml

When reviewing the TiDB-Binlog doc, we found the there is an difference between the pump config file and ansible pump config file. 
1. the gc in ansible pump config is default by 5. 
https://github.com/pingcap/tidb-ansible/blob/master/conf/pump-cluster.yml
2. the gc in pump config is default by 7.
https://github.com/pingcap/tidb-binlog/blob/master/cmd/pump/pump.toml
Tools think it will be better if unify them to 7.
i changed the gc default value in ansible from 5 to 7.

update Pump-cluster default value of gc in config

---

scripts/tikv_details.json

https://github.com/tikv/tikv/pull/4411 changed allocator stats name from "jemalloc_stats" to "allocator_stats". Update grafana config accordingly.
Tested by deploy a cluster and check grafana:
Signed-off-by: Yi Wu <yiwu@pingcap.com>

update tikv grafana allocator_stats name

---

scripts/lightning.json

1. Remove unnecessary metrics.
2. Rename exists metrics to make it more reasonable.

scripts: refine lightning metrics

---

scripts/binlog.json

- query using `job=binlog`, but it's pump and drainer
- Should display type but not job name

binlog.json: Fix node board and `sql query time`

---

inventory.ini
start.yml

Take advantage of the new `is_initialized` flag (https://github.com/pingcap/pd/pull/1555) in PD's cluster status API to avoid starting tidb-server before the first region having enough replicas.
I have tested following cases:
- `ansible-playbook start.yml` with 3 tikv-servers. It retries 2~3 times to wait for making up replicas.
- `ansible-playbook start.yml` with 2 tikv-servers. It retries 20 times then report an error.
- `ansible-playbook start.yml` with 2 tikv-servers and an old PD (which does not have the flag). The wait process is skipped.
Note: Previously, it was allowed to run a cluster configured as `max-replicas=3` but only has 1 tikv-server. After this PR it will be disallowed. User need to either set `max-replicas` to 1 or set …

make sure the first region is replicated before starting tidb

---

scripts/tikv_raw.json

Signed-off-by: siddontang <siddontang@gmail.com>
Mostly we don't need to check the Raw metrics, but some users who use TiKV Raw mode only need this. So we add a new dashboard for Raw TiKV.
The page looks:

ansible: add TiKV raw metrics dashboard

---

scripts/tikv_details.json

This PR added some metrics that shows GC's progress, and fixed TiKV AutoGC Working which is incorrect.
By the way, I don't know why the default time range is `now-5m`... so I changed it back to `now-1h`.
Also I don't know what's happening on the `gridPos` field...
@LinuxGit  PTAL thanks!

Add metrics about GC progress

---

scripts/tikv_details.json

In TiKV's grafana panel, the metric gcworker-too-busy in "GC tasks" lost its legend format, so it shows "{}" in its legend. This PR fixes it.

fix GC tasks legend format in tikv metrics and broken layout in TiKV's dashboard

---

conf/pump-cluster.yml
roles/check_system_static/tasks/main.yml
roles/pump_cluster/vars/default.yml

Add parameters to pump config

---

scripts/tidb.json

Cherry-pick parse & compile to release 2.1 #795 .

scrips: add parse & compile duration to tidb grafana (#795)

---

roles/local/tasks/binary_deployment.yml
roles/local/templates/binary_packages.yml.j2
roles/tispark/tasks/main.yml

because of this issue pingcap/tispark#933
tispark jar name changed from `tispark-core-*-SNAPSHOT-jar-with-dependencies.jar` -> `tispark-assembly-*-SNAPSHOT.jar`

change tispark jar name

---

roles/local/tasks/binary_deployment.yml
roles/local/templates/binary_packages.yml.j2
roles/tispark/tasks/main.yml

release-3.0 should depend on tispark-2.1.1 which is tispark's latest stable release, instead of depend on tispark's master branch.

tispark use 2.1.1 instead of master branch

---

scripts/tidb.json
scripts/tidb_summary.json

http://172.16.5.34:34125/d/000000011/test-cluster-tidb?orgId=1

 script: uniform interval factor and steppedLine in tidb_summary

---

roles/prometheus/files/tikv.rules.yml

Currently the alert will be triggered only if outdated request waited for long time. This PR changes to alert when any request wait for long time to cover more scenarios.
Additionally, `tikv_coprocessor_outdated_request_wait_seconds` will be removed in https://github.com/tikv/tikv/pull/5155.
- Merge https://github.com/tikv/tikv/pull/5155 first.

Alert when any request wait for long time

---

common_tasks/get_pd_name_tls.yml
excessive_rolling_update.yml
rolling_update.yml

Divide the pd node into two groups(leader and follower), upgrade the follower first, and finally upgrade the leader.
@LinuxGit @superlzs0476 PTAL

Optimization rolling update pd

---

common_tasks/get_pd_name_tls.yml
excessive_rolling_update.yml
rolling_update.yml

* Optimization rolling update pd

Optimization rolling update pd (#883)

---

roles/prometheus/files/tikv.rules.yml

@LinuxGit @superlzs0476 PTAL
reference #891

Update TiKV alert rules

---

scripts/tikv_details.json

- Add heatmap for _Region average written bytes_
- Add heatmap for _Region average written keys_
- Add histogram for _Approximate Region size_
- Change _MVCC versions_ to use histogram
- Change _MVCC delete versions_ to use Heatmap

grafana: use histogram and heatmap for some graphs

---

conf/drainer-cluster.toml

Drainer adds `ignore-txn-commit-ts config` config, this PR adds the config in ansible. 
TiDB Binlog: https://github.com/pingcap/tidb-binlog/pull/685

drainer: add ignore-txn-commit-ts config

---

conf/tikv.yml
roles/tikv/templates/tikv.toml.j2
roles/tikv/vars/default.yml

* Fix pessimistic-txn config of tikv.
* Remove `monitor-membership-interval` which has removed in https://github.com/tikv/tikv/pull/5028.

fix pessimistic-txn config of tikv

---

conf/tikv.yml
roles/tikv/templates/tikv.toml.j2
roles/tikv/vars/default.yml

fix pessimistic-txn config of tikv (#910)

---

roles/local/tasks/binary_deployment.yml
roles/local/templates/binary_packages.yml.j2
roles/tispark/tasks/main.yml

update tispark to 2.2.0 (release-2.1)

update tispark to 2.2.0 (release-2.1)

---

deploy.yml
excessive_rolling_update.yml
roles/check_config/tasks/check_pd_config.yml
roles/check_config/tasks/check_tidb_config.yml
roles/check_config/tasks/check_tikv_config.yml
roles/check_config/tasks/main.yml
rolling_update.yml

Check config before deploy or rolling_update

---

conf/tidb.yml
roles/tidb/vars/default.yml

via https://github.com/pingcap/tidb/pull/12041
@sykp241095 @youjiali1995  PTAL

Update tidb configuration

---

roles/check_system_dynamic/tasks/main.yml

When the user password has expired, the raw module will not report an error and will wait all the time.
@LinuxGit @sykp241095 PTAL

Update disk space check module

---

deploy.yml
roles/perf_tools/tasks/main.yml
scripts/funcslower
scripts/iosnoop

@zhouqiang-cl @sykp241095 PTAL

Add perf-tools: iosnoop and funcslower

---

roles/check_config_static/tasks/main.yml
roles/check_system_static/tasks/main.yml
roles/pre-ansible/tasks/coreos.yml
roles/pre-ansible/tasks/main.yml
roles/pre-ansible/tasks/root_tasks.yml

Replace raw module to shell

---

scripts/tikv_details.json

Add and update metrics of Titan.
The board may look like this:
blob get operations/duration is empty due to the related metrics is not added yet

tikv: update titan metrics

---

scripts/tikv_details.json

This PR cherry-picks https://github.com/pingcap/tidb-ansible/pull/761 and https://github.com/pingcap/tidb-ansible/pull/780 to release-3.0 branch.
#761 's changes are manually added to the code to avoid annoying conflicts.
Version controlling on the extremely-large json file works terrible.

Cherry pick GC progress and some fix to GC related metrics to release 3.0 branch

---

.gitignore
scripts/pd.json

This PR supports to select an individual store's metrics.
By setting this variable:
We can make some metrics more clear. e.g.

scripts: support to select an individual store

---

scripts/tidb.json

Add a metric for DDL add index speed.
Related TiDB PR: https://github.com/pingcap/tidb/pull/12374

tidb: add index speed metric

---

conf/pd.yml
conf/tidb.yml
conf/tikv.yml
roles/pd/vars/default.yml
roles/tidb/vars/default.yml
roles/tikv/vars/default.yml

Signed-off-by: lucklove <gnu.crazier@gmail.com>

reduce config items

---

scripts/tikv_details.json

Signed-off-by: Little-Wallace <bupt2013211450@gmail.com>
- Use `max`  instead of `avg` when calc max duration.
- Show `block-cache-size` by each instance
- Show cpu usage by each thread.

conf: update tikv grafana config

---

scripts/binlog.json
scripts/tidb.json

Preview:
TiDB:
Binlog:
Signed-off-by: Aylei <rayingecho@gmail.com>

Add tidb skip binlog count graph in tidb and binlog dashboards

---

scripts/tidb.json

`tso_async_wait` is misleading, so it's better to remove it from the grafana.
http://172.16.5.34:34125/d/000000011/test-cluster-tidb?orgId=1
The rule is now 
```
type!~"tso|tso_async_wait"
```
About the change, `!~` means 
> Select labels that do not regex-match the provided string.
https://prometheus.io/docs/prometheus/latest/querying/basics/

scripts/tidb.json: remove tso_async_wait from the grafana panel

---

roles/prometheus/files/tikv.rules.yml
scripts/overview.json

Signed-off-by: Breezewish <me@breeswish.org>
Note: For alert rules, a better way is to check per-thread cpu, because the thread number can vary.

Partially fix some incorrect raftstore dashboard

---

scripts/binlog.json

The 6.1.6 version of the dashboard json is not displayed in the Grafana version 4.6.3. Update binlog.json, compatible with version 4.6.3 Grafana.
@july2993 PTAL

Update binlog.json, compatible with version 4.6.3 grafana

---

roles/prometheus/files/pd.rules.yml

close #982 
I did not modify other alerting rules because they won't be affected by stale metrics reported by non-leader instance.
Signed-off-by: Aylei <rayingecho@gmail.com>

Consider PD leadership when calculating pd_cluster_status metric

---

roles/prometheus/files/tikv.rules.yml

Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>
The alert rule "TiKV GC can not work" checks whether `sum(increase(tidb_tikvclient_gc_action_result{type="success"}[6h])) < 1`. However when distrubuted GC is enabled, the metrics `tidb_tikvclient_gc_action_result`, which counts successful and failed regions of sending GC requests, will not be set. Therefore the alert will be triggered even if GC is running normally. 
This PR changes the expression to `sum(increase(tikv_gcworker_gc_tasks_vec{task="gc"}[1d])) < 1` , which is calculated on TiKV side.
This needs to be cherry-picked to release-3.x branches.

Update alert rule to work properly when distrubuted gc is enabled

---

scripts/overview.json

Remove tidb3, because it does not belong to tikv.
@rleungx PTAL

remove extra monitor content

---

conf/tidb.yml
roles/tidb/vars/default.yml

Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>
TiDB https://github.com/pingcap/tidb/pull/12884 has change default value for grpc connection count, keep consistent with TiDB.

tune grpc connection default value

---

roles/tidb/tasks/binary_deployment.yml
roles/tidb/templates/run_tidb_binary.sh.j2

Note: Need to install `numactl` on each tidb-server machine. If one machine is not installed `numactl`, will deploy tidb-server without bind numa node.
@sykp241095 @superlzs0476 PTAL

Add numa node bind for tidb-server

---

conf/tidb-lightning.yml
roles/tidb_lightning/vars/tidb-lightning.yml
scripts/lightning.json

1. In `tidb-lightning.toml`, include the new `[tikv-importer] backend` and `on-duplicate` settings.
2. In the Grafana dashboard,
* Added a panel to indicate if the TiKV is in Import or Normal mode
* Changed the storage size from always divide by 3 to the actual replicas setting.

tidb-lightning: expose the "backend" setting; update Grafana dashboard

---

scripts/performance_write.json
scripts/tidb.json

scripts: update 9999 to 999 for TiDB

---

roles/prometheus/files/tidb.rules.yml
scripts/tidb.json

Rename a TiDB metrics counter from `critical_error_total` to `binlog_error_total` and add alert rule for it.

add alert rule for tidb binlog error count

---

conf/tikv.yml
roles/tikv/vars/default.yml

Remove useless config. https://github.com/tikv/tikv/pull/5827

conf/tikv: remove storage.scheduler-notify-capacity

---

conf/drainer.toml

The `flash` downstream option has long been deprecated.
After pingcap/tidb-binlog#812 it would be removed from binlog.

drainer: Remove deprecated config value

---

scripts/pd.json

I try to add some metrics into `pd.json`. But there is some difference through import and export.
1. __input 
2. id 
3. datasource
4. `"current":{}`
5. uid and version
But there are some other unnecessary manual modify. So I open the pull request

avoid unnecessary manual modify when add metrics

---

create_users.yml

Modify create_users.yml to make it more friendly to mac users as their home dir is `/User/<username>` but not `/home/<username>`.

Modify create_users.yml.

---

roles/prometheus/files/tidb.rules.yml
scripts/overview.json
scripts/performance_read.json
scripts/performance_write.json
scripts/tidb.json

scripts: use one backoff metric for KV backoff

---

conf/tikv.yml

Adding rocksdb.titan config section back to allow users discover the feature and try it. Also removing configs not mean to be use normally.
Signed-off-by: Yi Wu <yiwu@pingcap.com>

Update and simplify Titan config in tikv config template

---

scripts/tidb.json
scripts/tidb_summary.json

Avoid using `tidb_tikvclient_txn_cmd_total` for KV request which will confuse the user.

scripts: update the KV metrics on TiDB

---

scripts/overview.json
scripts/tidb.json
scripts/tidb_summary.json

1. Remove KV snapshot
2. Add KV Transaction Duration
3. Reorg transaction panel move the transaction wared panels together.

scripts: update txn metrics

---

migrate_monitor.yml
rolling_update_monitor.yml
scripts/br.json
scripts/grafana-config-copy.py
start.yml

scripts:add backup & restore dashboard

---

scripts/tidb.json

The add index progress = (added row count) / (total row count).

scripts/tidb: add panel for ddl add index progress

---

scripts/tidb.json

tidb related change
https://github.com/pingcap/tidb/pull/14527
example:
http://172.16.5.73:23335/d/000000011/rnew_3_0-tidb?orgId=1&from=1580885071443&to=1580885976444

add pessimistic retry count panel in tidb transaction tab

---

scripts/tikv_details.json

Signed-off-by: 5kbpers <tangminghua@pingcap.com>
Add uptime metric into 'tikv-details' dashboard.

tikv-details: add uptime metric

---

group_vars/tiflash_servers.yml
roles/tiflash/defaults/main.yml
roles/tiflash/tasks/main.yml
roles/tiflash/templates/tiflash_learner.toml.j2

cherry pick https://github.com/pingcap/tidb-ansible/pull/1140

[cherry-pick] add tiflash proxy status port config (#1140)

---

roles/check_config_static/tasks/main.yml
roles/grafana/templates/data_source.json.j2
roles/prometheus/templates/prometheus.yml.j2
rolling_update_monitor.yml
scripts/grafana-config-copy.py
start.yml

* Support multiple monitor nodes

Support multiple monitor nodes (#1137)

---

conf/tiflash-learner.yml
conf/tiflash.yml
deploy.yml
excessive_rolling_update.yml
group_vars/tiflash_servers.yml
inventory.ini
roles/common_dir/tasks/main.yml
roles/local/tasks/binary_deployment.yml
roles/local/templates/binary_packages.yml.j2
roles/prometheus/templates/prometheus.yml.j2
roles/tiflash/defaults/main.yml
roles/tiflash/meta/main.yml
roles/tiflash/tasks/binary_deployment.yml
roles/tiflash/tasks/main.yml
roles/tiflash/tasks/supervise_deployment.yml
roles/tiflash/tasks/systemd_deployment.yml
roles/tiflash/templates/run_tiflash_binary.sh.j2
roles/tiflash/templates/tiflash.toml.j2
roles/tiflash/templates/tiflash_learner.toml.j2
roles/tiflash/vars/tiflash-learner.yml
roles/tiflash/vars/tiflash.yml
rolling_update.yml
start.yml
stop.yml
unsafe_cleanup.yml

release-3.1: support tiflash

---

conf/pd.yml
roles/pd/vars/default.yml

Based on #978, especially remove `namespace-classifier` for the compatibility problem.

roles: remove pd namespace config

---

roles/check_system_dynamic/tasks/main.yml
roles/check_system_static/tasks/main.yml
roles/tikv/tasks/check_filesystem.yml

via #1163 
* fix 404 url
* update ntp check url

fix 404 url (#1163)

---

roles/dashboard_topo/templates/init_dashboard_topo.sh.j2
scripts/dashboard_topo.py

This pr support prometheus in dashboard topology. Which is decleared in this issue: https://github.com/pingcap-incubator/tidb-dashboard/issues/168

Support Prometheus in for dashboard topology

---

deploy.yml
excessive_rolling_update.yml
roles/dashboard_topo/tasks/main.yml
roles/dashboard_topo/templates/init_dashboard_topo.sh.j2
rolling_update.yml
scripts/dashboard_topo.py
start.yml

release-4.0: Support Inject cluster topology information for am and grafana to etcd in pd

---

roles/ops/templates/pd-ctl.sh.j2

In newer versions, the pd-ctl interactive mode parameter is changed to -i, corresponding to tidb-ansible also needs to be changed.

update pd-ctl.sh.j2 for release-3.0 (#1213)

---

roles/ops/templates/pd-ctl.sh.j2

In newer versions, the pd-ctl interactive mode parameter is changed to -i, corresponding to tidb-ansible also needs to be changed.

update pd-ctl.sh.j2 for release-3.1 (#1213)

---

roles/ops/templates/pd-ctl.sh.j2

In newer versions, the pd-ctl interactive mode parameter is changed to -i, corresponding to tidb-ansible also needs to be changed.

update pd-ctl.sh.j2 (#1213)

---

conf/tidb.yml
roles/tidb/vars/default.yml

config, roles: add config of server-version.

---

conf/tikv.yml
roles/tikv/vars/default.yml

https://github.com/tikv/tikv/pull/7234 changes the default configuration of tikv, making it not use the unified pool to handle storage requests. Synchronize ansible with that change.
DNM until https://github.com/tikv/tikv/pull/7234 is merged.
Note that this PR should be cherry-picked to 4.0.

sync unified read pool default configurations with tikv#7234

---

conf/tidb.yml
roles/tidb/vars/default.yml

config, roles: add config of server-version (#1231)

---

roles/tidb/templates/run_tidb_binary.sh.j2

Go 1.13 use `MADV_FREE` which will cause RSS don't shrink even if heap size is shrunk.
Set `madvdontneed=1` in `GODEBUG` will ask runtime use `MADV_DONTNEED`, which will shrink RSS size more quickly.

set madvdontneed=1 to shrink RSS after GC

---

roles/tiflash/defaults/main.yml

cherry pick https://github.com/pingcap/tidb-ansible/pull/1270

let tiflash tmp_path use DataDir instead of DeployDir (#1270)

---

scripts/tiflash_summary.json

Related pr: https://github.com/pingcap/tics/pull/644.
Need cherry-pick to 3.1 and 4.0

Add TiFlash storage metrics in grafana

---

conf/tikv.yml
roles/tikv/vars/default.yml

Fix tikv config check failure on deploy due to wrong format of config template:
```
[TiKV1-1]: Ansible Failed! ==>
changed=true
cmd: cd /tmp/tidb_check_config && ./tikv-server --pd-endpoints pd:port --config ./tikv.toml --config-check
delta: '0:00:00.524112'
end: '2020-05-25 14:35:13.870777'
msg: non-zero return code
rc: 101
start: '2020-05-25 14:35:13.346665'
stderr: |-
thread 'main' panicked at 'invalid auto generated configuration file ./tikv.toml, err missing field `type` for key `security.encryption.master-key`', /rustc/b2e36e6c2d229126b59e892c9147fbb68115d292/src/libstd/macros.rs:16:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
stderr_lines:
- thread 'main' panicked at 'invalid auto generated configuration file ./tikv.toml, err missing field `type` …
```

Fix tikv config check failure on deploy

---

conf/tikv.yml
roles/tikv/vars/default.yml

Fix tikv config check failure on deploy due to wrong format of config template:
```
[TiKV1-1]: Ansible Failed! ==>
changed=true
cmd: cd /tmp/tidb_check_config && ./tikv-server --pd-endpoints pd:port --config ./tikv.toml --config-check
delta: '0:00:00.524112'
end: '2020-05-25 14:35:13.870777'
msg: non-zero return code
rc: 101
start: '2020-05-25 14:35:13.346665'
stderr: |-
thread 'main' panicked at 'invalid auto generated configuration file ./tikv.toml, err missing field `type` for key `security.encryption.master-key`', /rustc/b2e36e6c2d229126b59e892c9147fbb68115d292/src/libstd/macros.rs:16:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
stderr_lines:
- thread 'main' panicked at 'invalid auto generated configuration file ./tikv.toml, err missing field `type` …
```

Fix tikv config check failure on deploy (#1306)

---

scripts/tikv_details.json

Add metric of Grafana for perf-context. This metric could help us better know why write performance RocksDB slow down.
See more details in https://github.com/tikv/tikv/pull/7354

add metric for perf-context

---

scripts/tikv_details.json

If we choose one specific instance in `grafana`/`tikv-detail`, then the data of `Block cache hit` panel will be not right, the reason the queries missed part of the filters `by instance`.
This PR fixes that.

Fix queries of block cache hit panel

---

scripts/overview.json

Signed-off-by: Shafreeck Sea <shafreeck@gmail.com>
The balance ratio has been abandoned from 3.0. Use `Normal stores` which keeps the same with the master branch.

pd: remove balance ratio from the overview dashboard

---

rolling_update_monitor.yml
scripts/grafana-config-copy.py
scripts/tiflash_proxy_details.json
scripts/tiflash_summary.json
start.yml

cherry-pick of #1321 to release-3.1
* * *
- Add a new dashboard in Grafana to show more metrics about TiFlah-Proxy
- Change the unit of the panels of DDL jobs in Grafana to operations per minute

Add details dashboard for TiFlash-Proxy (#1321)

---

scripts/tiflash_proxy_details.json
scripts/tiflash_proxy_summary.json
scripts/tiflash_summary.json

Signed-off-by: JaySon-Huang <tshent@qq.com>
* Grafana: 
* TiFlash-Summary
* Add line for write amplification for last 5 minute
* Add panel for CPU/memory usage
* Add panel for Fsync/Newly Opened File/Opened File Count
* Add panel for Disk Read/Write OPS
* Add panel for Disk read/write flow (bytes per second)
* Add panel for the rough set filter rate for last 1 minute
* Add panel for store used/available/capacity size
* Split the duration of "delta_merge" on Internal Tasks Duration since it takes few seconds while other operation only take tens or hundreds of ms
* TiFlash-Proxy-Summary/Details
* Remove store used/available/capacity size
Check http://172.16.5.85:21518/d/SVbh2xUWk/jtest-tiflash-summary?orgId=1&refresh=30s for details.

Add more metrics about IO operations and store size for TiFlash

---

scripts/tiflash_proxy_details.json
scripts/tiflash_proxy_summary.json
scripts/tiflash_summary.json

cherry-pick of #1343 
* * *
Signed-off-by: JaySon-Huang <tshent@qq.com>
* Grafana: 
* TiFlash-Summary
* Add line for write amplification for last 5 minute
* Add panel for CPU/memory usage
* Add panel for Fsync/Newly Opened File/Opened File Count
* Add panel for Disk Read/Write OPS
* Add panel for Disk read/write flow (bytes per second)
* Add panel for the rough set filter rate for last 1 minute
* Add panel for store used/available/capacity size
* Split the duration of "delta_merge" on Internal Tasks Duration since it takes few seconds while other operation only take tens or hundreds of ms
* TiFlash-Proxy-Summary/Details
* Remove store used/available/capacity size

Add more metrics about IO operations and store size for TiFlash (#1343)

---

conf/spark-defaults.yml

see: https://github.com/pingcap/tispark/pull/1597

update spark.tispark.grpc.framesize default value

---

conf/spark-defaults.yml

cherry pick https://github.com/pingcap/tidb-ansible/pull/1349

update spark.tispark.grpc.framesize default value (#1349)
